### ISSUE TITLE
[Doc update] View context not accessible as the doc says

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#1000]
Accessing `current_user` in the `Avo::Resource` is not as straightforward as [the doc implies](https://docs.avohq.io/2.0/customization.html#context).
When declared the way it is exposed in `avo.rb`, `current_user` is accessible through `context[:user]` instead of `current_user`.

### Steps to Reproduce
1. Set the `set_context` option as per the doc (follow link above)
2. Call `current_user` in the resource
3. Watch it fail

### Expected behavior
It should not break, and `current_user` should be accessible. Maybe `user` would actually make more sense ? (ie, using the keys of the `context` hash directly)

### Actual behavior
`current_user` is not available, which doesn't sound really surprising. But I would have expected `user` to work though. Having to call `context[:user]` feels a bit clumsy.

### System configuration
**Avo version**: 2.9

**Rails version**: 6?1

**Ruby version**: 2.7

**License type** (Community or Pro): Pro

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by bear-in-mind** [comment]
Hey @adrianthedev !
Thanks for being so quick, as always :)
Here is the way it's configured:
```ruby
# avo.rb
## == Set the context ==
config.set_context do
  {
    user: current_user
  }
end

## == Authentication ==
config.current_user_method = :current_user
```
I'm trying to access `current_user` in a resource file.

**Comment by adrianthedev** [comment]
Thanks for the code details. THey always help to create the larger picture.

Avo uses lambda's (like it does on `resolve_query_scope`), but not all of them are run in the same environment. Not all of them have access to all the things (`params`, `current_user`, `view_context`, and other things specific to them.

In the docs I try to specify for each lambda the things the developer has access to ([example](https://docs.avohq.io/2.0/menu-editor.html#item-visibility), [another example](https://docs.avohq.io/2.0/resources.html#resource-description)).

In the beginning of Avo I would just pass into the lambda the things that you'd need to access, but that introduced breaking changes very easy when I needed to add more arguments, so I went another way and introduced `Evaluation Hosts` (which should be named `Execution Contexts`). These are POROs that hold all the necessary information like `current_user`, `params`, `view_context` and all the other tiny things one would need in their lambdas. More on them [here](https://docs.avohq.io/2.0/evaluation-hosts.html#what-s-a-host).
They work very well with our model, but I haven't yet backported all the lambdas in Avo to them, `resolve_query_scope` being one of them. 

Here's how `resolve_query_scope` (old behavior) executes [here](https://github.com/avo-hq/avo/blob/main/lib/avo/base_resource.rb#L81) and how a `visible` from the menu builder (new behavior) gets executed in a isolated context [here](https://github.com/avo-hq/avo/blob/main/lib/avo/menu/base_item.rb#L17).

I'd love it if in the future I (or if someone would like to pick this refactor up) could translate all of the old behavior to the new one.
Propably, the easiest fix here is to make a PR to delegate `current_user` to `::Avo::App` somewhere around [here](https://github.com/avo-hq/avo/blob/main/lib/avo/base_resource.rb#L19).

That's why sometimes you have direct access to `current_user` and sometimes you don't.

**Comment by adrianthedev** [comment]
Sure thing buddy ❤️

🍾 for the next thousand!

![afb8b2e8-d75d-4e49-9ceb-44ba977b1bd3](https://user-images.githubusercontent.com/1334409/176382627-3085b840-64de-4bfe-bf14-6ec22903480f.png)

**Comment by bear-in-mind** [comment]
Can't thank you enough 😇
