### ISSUE TITLE
Resource cards

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1072]
Add the ability to add cards to the resource, similarly to how we do it on a dashboard.

**Comment by Paul-Bob** [comment]
@adrianthedev I made this PR as a POC [feature: dashboards on resources](https://github.com/avo-hq/avo-dashboards/pull/16).

It do not respect the request since it's allowing to add dashboards to the resource instead cards. When I started implement it, I started with cards as the original request, however I realized that we already have the whole system done with the dashboards and we can keep it stupid simple by reusing that system.

This PR allow to declare dashboards on any resources by using the following syntax:
```ruby
  def dashboards
    dashboard Avo::Dashboards::Dashy
  end
```

All the dashboards declared on the resource will be rendered on top of the main panel on each view. Each dashboard is initialized with the `resource` attribute configured, that means the developers can to access the `resource` on the `cards` method or even on the `self.name` or `self.description`. The resource is already hydrated with the `view`, `record`, `params` etc... making it enough customizable for each case.

I don't want to invest more time in this feature without your approval since this is not the original request. Anyway I think this path is the right to follow, if we have the whole system build for `dashboards` why would we separate the `cards` into two different ways to maintain it?

We can make it more complex by allowing the developer to chose where to render it and even more customization. Let me know what do you think about this approach, I tried to apply the KISS principle and make usage of an already build system.

**Comment by Paul-Bob** [comment]
Re-implement as the original request
