### ISSUE TITLE
Taking a long time to load edit view with a belongs_to field and a lot of records

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1159]
Context
Related to #1134. When opening a form, it will take over a minute to load the page, which remains not responsible. The page takes a long time to load and when the belongs to field is clicked, Chrome dies.

This is the definition of the resource which the view is broken:

```
class ProductPriceResource < Avo::BaseResource
  self.title = :id
  self.includes = []
  # self.search_query = ->(params:) do
  #   scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)
  # end

  field :id, as: :id
  field :product, as: :belongs_to, searchable: true
  field :price, as: :number
end
```

And this is the related resource (33k records):

```
class ProductResource < Avo::BaseResource
  self.title = :name
  self.includes = []
  self.search_query = ->(params:) do
    scope.ransack(id_eq: params[:q], m: "or", name_cont: params[:q], ean_cont: params[:q]).result(distinct: false)
  end

  field :id, as: :id
  field :name, as: :text
  field :ean, as: :text
  field :company, as: :belongs_to, searchable: true
  field :product, as: :belongs_to, searchable: true

  tabs do
    field :products, as: :has_many
    field :product_measure_conversions, as: :has_many
    field :product_parameters, as: :has_many
    field :product_prices, as: :has_many
  end
end
```

System configuration
Avo version: 2.12.0

Rails version: 7.0.3

Ruby version: 3.1.2

License type (Community or Pro): Pro (trial)

**Comment by adrianthedev** [comment]
Which page are you trying to load and takes time? Can you share the path?

**Comment by alansikora** [comment]
Sometimes it loads the screen, this is the first time it breaks before loading it.

The path is: `/crud/resources/product_prices/new`, where `crud` is the `avo` root.

https://user-images.githubusercontent.com/575138/186184464-68e5b62e-a28f-4ccd-a599-a660354dcbe8.mp4

**Comment by adrianthedev** [comment]
The license key you're using is invalid, thus rendering the Pro license invalid.

Even if you have configured the fields to be `searchable`, because the `searchable` option is a part of the Pro license and the license is invalid, the fields are rendered as regular fields (not-searchable), thus having that issue.

So the resolve here is to have a valid license key.

![CleanShot 2022-08-23 at 18 11 32@2x](https://user-images.githubusercontent.com/1334409/186195296-666352f5-686f-4a10-b0a7-40fd17a64434.jpg)
