### ISSUE TITLE
Action dropdown issue: click only works on the icon

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1245]
### Describe the bug
The action only works when clicking on the icon of the action, the text does not work.

### Steps to Reproduce
Click on an action

### System configuration
**Avo version**: 2.15.3

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

### Screenshots

https://user-images.githubusercontent.com/575138/191134665-49e0b376-50cf-480c-83cc-ea7c35920de6.mp4

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Thanks for getting back to us with this 🙌

That's actually a bug. So the action you are showing is disabled because you haven't selected any records. I you want to run actions without selecting records, then you should use [standalone actions](https://docs.avohq.io/2.0/actions.html#standalone-actions).

The bug you're seeing is that you can click an icon and run the action when you shouldn't be able to do that.

**Comment by alansikora** [comment]
Ok, and is it possible to have an action that runs on the entire table?

This is somewhat related to #1248

**Comment by Paul-Bob** [comment]
> Ok, and is it possible to have an action that runs on the entire table?
> 
> This is somewhat related to #1248

Hey @alansikora, since Avo 2.14 we are able to select all records from the entire table (with the current filters applied), then if you run an action it will run on all that records. 

![CleanShot 2022-08-23 at 13 09 57](https://user-images.githubusercontent.com/1334409/186132482-8a04d117-a097-4378-884f-5a2d35f4280f.gif)

**Comment by adrianthedev** [comment]
> Ok, and is it possible to have an action that runs on the entire table?
> 
> This is somewhat related to #1248

Or the alternative is to create a [standalone action](https://docs.avohq.io/2.0/actions.html#standalone-actions), and you can run that on all records.

**Comment by Paul-Bob** [comment]
> > Ok, and is it possible to have an action that runs on the entire table?
> > This is somewhat related to #1248
> 
> Or the alternative is to create a [standalone action](https://docs.avohq.io/2.0/actions.html#standalone-actions), and you can run that on all records.

That's a possibility if you don't care about applied filters and just want to run the action on all records
