### ISSUE TITLE
Expand resource controls block for index and edit

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#1254]
### Feature

Avo have this `self.show_controls = -> do` cool customization but unfortunately it's not possible to customize the resource controls on index page. It would be useful to have this option for index page too, or maybe a `self.controls = -> do` and use the `show_on`, `hide_on`, `except_on` and the other visibility options for each control.

**Comment by nicholaswellens** [comment]
@Paul-Bob @adrianthedev I have an issue that seems related: it does not seem possible to configure the visibility of seperate action buttons (so defined in `self.show_controls` instead of just existing in the `actions_list`, as shown in [this video](https://www.youtube.com/watch?v=qUvMh7AkrlU&t=320s&ab_channel=Avo)). In other words: `self.visible` action attribute does not work with `self.show_controls`

**Comment by Paul-Bob** [comment]
Hello @nicholaswellens. If i understand you have a visibility option on your action to hide it on show and it appear on show because you put it inside `show_controls` ? If that's the case I think we are not facing an issue, you are just overriding the visibility by telling Avo you want that action o `show_controls`

**Comment by nicholaswellens** [comment]
@Paul-Bob that was exactly my issue! Thank you for the solution/explanation, it indeed makes sense to use the conditionals within the `show_controls` block in this case!

**Comment by Paul-Bob** [comment]
@adrianthedev yes, I agree with separate blocks, that give to the developer more control of each part even if there is some duplicated code

**Comment by adrianthedev** [comment]
For `row` let's see if we can enable the user to add buttons before or after the fields using this DSL.

Ex:

```ruby
self.row_controls = -> do
  action SomeAction
  delete_button
  fields
  detach_button
  edit_button
end
```

**Comment by Paul-Bob** [comment]
Already implemented on Avo3.
