### ISSUE TITLE
search input got rendered multiple time

### ISSUE THREAD

**Issue by elassadi** [avo-hq/avo#1331]
### Describe the bug

Search input are wrongly rendered multiple times after you hit the browser back button.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/1938264/196647178-37b7a954-09f5-426f-ace9-f428414c85f5.png">

### Steps to Reproduce
![avo-search-input-bug](https://user-images.githubusercontent.com/1938264/196648595-31fb884d-b717-433e-b4e8-80447c3a5c80.gif)

1. use latest Avo release or checkout: [avo-demo](https://github.com/elassadi/avo-demo)
2. Go to any resource with search enabled 
3. Click on browser back button 
4. a second search input will be rendered just below the existing one

### Expected behavior & Actual behavior

Only one search button schould be visible

### System configuration
**Avo version**: latest 2.17

**Rails version**: 7.0.4

**Ruby version**:3.0.1

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Yup. It's a bug. We gotta clean up the artifacts somehow.

If you have any experience with stimulus JS and custom js plugins, we're open for PRs.

Thanks for reporting.

**Comment by rajaravivarma-r** [comment]
@adrianthedev This bug is preventing us from going with the upgrade. Could you please point me to a place where the *artifacts* are, so that I can give a shot at fixing it?

**Comment by adrianthedev** [comment]
### Approach

The issue is that the js plugin (`autocomplete` found in `search_controller.js`) is not properly cleaning up the input when the user navigates away from the page.

What I'd look into is running the [`destroy`](https://www.algolia.com/doc/api-client/getting-started/update/javascript/?client=javascript#the-destroy-method) method on the autocomplete js plugin. That should reset things to how they were (supposedly).

If that doesn't work, I would do something like this. On the [`date_field_controller`](https://github.com/avo-hq/avo/blob/main/app/javascript/js/controllers/fields/date_field_controller.js#L77) is to use the `disconnect` method to "reset" the state back to what it was.

One thing is for sure, what should be left in place, is the same thing that was when the page was loaded in `_global_search.html.erb` and `_resource_search.html.erb`, so when the user navigates back, the search controller can pick it up and get initialized again.

**Comment by rajaravivarma-r** [comment]
Cool. I'll see if I can fix this.
