### ISSUE TITLE
@mention feature in trix editor

### ISSUE THREAD

**Issue by mighani** [avo-hq/avo#1417]
### Feature

@Mention in trix editor
typing "@" opens a small window showing matching entries in a user table. I can navigate with cursor down or up, or type additional letters, which will narrow down the filter. Hitting enter will choose the user from the table and insert a mention of the user in the trix editor. Saving the model will then send out an email to the mentioned users.

### Current workarounds

Actually, I have created an after commit hook like: after_commit :notify, if: :saved_change_to_note?
The notify method will parse the note for "@" letter and with regex I get the mention string. I then look up the mention string (which represents a short name of the user) in the user table. Get the email address and send out an email.

**Comment by adrianthedev** [comment]
I see. I haven't worked with trix that much and I'm not sure if it supports that kind of behavior. 

I think the best way here would be to duplicate the Trix field and start to experiment and see if that @ dropdown can be added. 

Otherwise, the only thing left would be to create a route and controller to return the users to you.

**Comment by adrianthedev** [comment]
Closing for now. feel free to reopen if you have new information.
