### ISSUE TITLE
Authorization policy is not applied correctly

### ISSUE THREAD

**Issue by elassadi** [avo-hq/avo#1459]
### Describe the bug

Comment Edit button is still shown, although the Comment policy is set to disallow edit action. 

```ruby

class CommentPolicy < ApplicationPolicy


  def new?
    create?
  end

  def update?
    false
  end

  def edit?
    update?
  end
.....
  end
```
Clicking the edit button will result in redirect to the index page , since the policy dont allow edit the record 

![image](https://user-images.githubusercontent.com/1938264/204157735-df9abcbf-b15a-41fb-a0a2-028b66a58c03.png)

### Steps to Reproduce
1. checkout the demo code https://github.com/elassadi/avo-demo
2. create a post and a comment 
3. hit http://127.0.0.1:3000/avo/resources/posts/1
4. comment edit button is shown 

### Expected behavior & Actual behavior

Edit button should be hidden

### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

**License type**:

 - [x] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @elassadi. Being in an association, you can set those authorization rules in the `PostPolicy` using the `edit_comments?` method. 

[Docs](https://docs.avohq.io/2.0/authorization.html#associations).

**Comment by elassadi** [comment]
Hi @adrianthedev 

Beside the fact that is totaly unusual to set the policy of editing a record in the association policy. 
this will means we will need to assign edit_comments in any resources associating comments 
and additional to that the user should have the right to edit comment as well. 

this is not consistent in both cases it sounds weared.

use cases
1- Allow user to edit comments in the Post policy will run into redirect ( without knowing what's wrong) if we don't give him the edit authorization in the comment policy 


2- assume the comment policy is allowing to edit only the comments made by the current_user,
something like
``` ruby
user.can :edit, owner: current_user

```
Associated index table will show all record with an edit button. Which is misleading. 

if the user is allowed to edit the comments should be restricted to the comment policy.
show_comments,  on the other hands should be in the post policy. 

Digging into the code shows the problem in its core. The association authorization is relaying on the parent association model, therefor the authorization service will not be able to authorize a record correctly. 

 ``` ruby
def authorize_association_for(policy_method)
    policy_result = true

    if @reflection.present?
      # Fetch the appropiate resource
      reflection_resource = field.resource
      # Fetch the model
      # Hydrate the resource with the model if we have one
      reflection_resource.hydrate(model: @parent_model) if @parent_model.present?
      # Use the related_name as the base of the association
      association_name = @reflection.name

      if association_name.present?
        method_name = "#{policy_method}_#{association_name}?".to_sym
        # Prepare the authorization service
        service = reflection_resource.authorization

        if service.has_method?(method_name, raise_exception: false)
          policy_result = service.authorize_action(method_name, raise_exception: false)
        end
      end
    end

    policy_result
  end
```

I hope we can get more consistency in the design of the authorization for now, to be honest, I have some doubt how 
to adapt it. to our RBAC system which is dynamically create and allow creating rules and policies  on the fly.

**Comment by adrianthedev** [comment]
Thanks for sending in your thoughts. As always, they are greatly appreciated.

I know the system isn't perfect.
From the no.1 use case, you pointed out, yes. That would be what would happen, and it's not the best experience for the user. The developer will have to make sure that the right validation is set in the `CommentPolicy`, not just `PostPolicy`.

I think that we reached this point from the initial design of using the authorization policies to control which buttons are visible or not. Going from that, it made more sense having all association-related controls in the parent policy to avoid confusion. 
It's like, if you want to control the authorization in the main resource, you operate the main policy, but if you want to control the authorization for the associated resource, then do it from the association policy.

I'm not saying that this is the best approach, but it does give you the flexibility, to control whether you want to display/hide the view/edit/delete buttons in **each view** (resource or association), not just **apply the same rule for all of them**.


### I found a bug

I wrote all of the above and set out to show you a way to make this work with your current authorization library, but I found a bug.
I'm not sure if this is what you meant to say in your message, but I didn't get that.

So, in the (let's say) `edit_comments?` method, the `record` that we're getting now is the parent (an instance of `Post`), instead of the actual record (an instance of `Comment`), and that's wrong.
You can't authorize each `Comment` based on the parent.

That would fix your issue with `user.can :edit, owner: current_user`, right?

We'll fix that in the next release.

Thanks for insisting!

**Comment by adrianthedev** [comment]
Also, now, to avoid duplication, you could set the `edit_comments?` like so.

```ruby
class PostPolicy
  def edit_comments?
    Pundit.policy!(user, record).edit?
  end
end
```

This will find the `CommentPolicy` and use that rule? And you wouldn't have to ever touch the `PostPolicy` to change the authorization logic for the comments.

Would that work for your use case?
