### ISSUE TITLE
Empty state translation is missing item name in 2.21

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1487]
### Describe the bug

After upgrading to 2.21 the text for the empty state component (used for has many associations) has changed from (if your model `has_many :people`) `No related people found` to `No related %{item} found`.

### Steps to Reproduce
1. Create a resource with `field :people, as: :has_many` and a model with `has_many :people`
2. Create a new resource
3. On the show page, look for the empty state for the has many field

### Expected behavior & Actual behavior

It should say "No related people found" but instead shows "No related %{item}" found.

### System configuration
**Avo version**: 2.21

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

![Screenshot 2022-12-09 at 11 38 39](https://user-images.githubusercontent.com/111963/206694374-c1e78d12-1902-457d-ba9e-39f31a002f7c.jpg)

### Additional context

Looks like it was introduced in [this commit](https://github.com/avo-hq/avo/commit/3b98369e174308a04de3075554c0178c798e9ba0) when the translations for the empty state component were refactored. I'd fix it but it's not clear to me what the correct fix should be here.

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

(I can't upgrade to 2.21 until this is fixed)

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
@Paul-Bob can you look into this when you have some spare time please?

**Comment by Paul-Bob** [comment]
Hey @iainbeeston. Thanks for the details, I'm doing an PR to update de upgrade guide. Basically we have this changes and maybe you did not update your locale files (i forgot to mention it on upgrade guide, my bad).

```ruby
# Before
no_item_found: No %{item} found
no_related_item_found: No related %{item} found

# After
no_item_found: No record found
no_related_item_found: No related record found
```

In English it works just fine but in other languages it's hard to make it right because some words should be plural others singular other masculine others feminine and it's hard to make it work with that translation templates because we were allays pluralizing the name of the resource. One of the fixes for that can be using the i18n plurals + i18n context but that would add some unnecessary complexity.

What do you think about this, were that custom messages for each table important for your use case? Should we invest to make it customizable in the future or a generic message it's enough?

**Comment by adrianthedev** [comment]
Closed by mistake. Sorry.

So the fix here is to run `bin/rails generate avo:locales --force`, and that will fix the missing locales?

**Comment by Paul-Bob** [comment]
> Closed by mistake. Sorry.
> 
> So the fix here is to run `bin/rails generate avo:locales --force`, and that will fix the missing locales?

I think yes.

https://github.com/avo-hq/avo/blob/3b98369e174308a04de3075554c0178c798e9ba0/lib/generators/avo/templates/locales/avo.en.yml#L68

As we can confirm the `No related %{item} found.` is not in our locales, it has changed to `No related record found `  on last release.

**Comment by iainbeeston** [comment]
@adrianthedev That helps a little bit, but now instead of `No related people found` I get `No related record found`, which isn't very user friendly (it doesn't tell users what kind of record) and isn't very good English (I'd expect it to say `No related record found` for a belongs to or has one, but `No related records found` for a has many where there could be more than one - basically the same `pluralize` helper, which in English uses plural for zero records). Is there any way to get the old behaviour back? Or is this necessary to make the code work cleanly?

**Comment by adrianthedev** [comment]
Yeah, I see your point. The issue is a bit gnarlyier. You can see [this convo here](https://github.com/avo-hq/avo/pull/1433#discussion_r1034111106).

The issue is that it's difficult to localize the message and the resource name in different languages.
Ex: in English you would say `No related PLURALIZED_RESOURCE_NAME found` (no related cars found), but in portughese it's `No related SINGULARIZED_RESOURCE_NAME found` (no related car found), so it's impossible to control that from the `yml` file.

I think the easiest thing you could do to get back that behaviour is to override that component (manually copy it from [here](https://github.com/avo-hq/avo/blob/main/app/components/avo/empty_state_component.rb) and [here](https://github.com/avo-hq/avo/blob/main/app/components/avo/empty_state_component.html.erb) into your app under the same directory) and manually override the message.

We'll fix the bad English, not sure how it went through.

We have an idea on how to do that in a more extendable way but I don't think we'll tackle it very soon. Maybe for Avo 3.

**Comment by iainbeeston** [comment]
That sounds fine, maybe it should be possible to have a different translation for each resource? I’ll close this issue and on my own project I will update the English translation to plural and use “no related resources” for everything

**Comment by iainbeeston** [comment]
Btw thanks for taking the time to explain why this had to change!
