### ISSUE TITLE
Use of simple_form or formtastic, and their versions of fields_for

### ISSUE THREAD

**Issue by simonhutchings** [avo-hq/avo#1499]
### Feature
Ability to easily add nested fields. And build them before presenting the form. For example with translations in globalize

```
    I18n.available_locales.each do |language|
      @model.translations.new(locale: language)
    end
```

what i'd like to do is have a tab for each language

```
  tabs do
    
    @resource.model.translations.each do |lang|
      fields_for lang do
      tab lang.upcase do
        panel do
          field :name, as: :tex
          # field :slug, as: :text, locale: lang
        end
      end
    end

  end
```
### Current workarounds
Not sure. I've used Active Admin for many years and was easy within there, but recently have been just writing my admin interfaces from scratch

**Comment by adrianthedev** [comment]
We don't currently have the multilingual content built into Avo as a first-party feature, but there's a way to get that kind of feature.


This is what you could:

```ruby
  tabs do
    ["en", "fr"].each do |locale|
      tab locale do
        panel do
          field :"name_#{locale}", as: :text
        end
      end
    end
  end
```

Basically, "hardcode" the locales instead of trying to get them from the model. On build-time, that block does not have access to the resource or record.

We'd like to bring the official multilingual feature into Avo 3.0

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen.
