### ISSUE TITLE
Location field

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#1513]
Hi,

Could a field be added for a location.    Maybe it could display as a marker on a map and the ability to type the lat and lng in directly.  Then store in a variety of ways.  I typically store in separate lat and lng fields.

**Comment by adrianthedev** [comment]
Yes, that would be nice to have. I would merge a PR if there was one open.

**Comment by yondifon** [comment]
Saw this from Beginner Boutines. Can I send in a PR?

**Comment by adrianthedev** [comment]
Hey @yondifon. Thanks for wanting to contribute.
The goal of the Beginner Boutines app is to help beginners get into Ruby development.

Do you consider yourself a junior developer?

**Comment by yondifon** [comment]
In the Ruby space. Yes. 

but I have some experience in other communities.

**Comment by adrianthedev** [comment]
Sounds good @yondifon! 
Yes. Go for it!

**Comment by adrianthedev** [comment]
And thank you!

**Comment by adrianthedev** [comment]
I'm writing an approach now

**Comment by adrianthedev** [comment]
## Approach:

I'll use the Trix field as an example because it should be similarly built.
You'll need to produce a few files:

 - the field file ([example](https://github.com/avo-hq/avo/blob/main/lib/avo/fields/trix_field.rb)). That registers the field with Avo. It also holds some options that are specific to that field (`always_show`, `attachments_disabled`, etc.)
 - the view components ([show](https://github.com/avo-hq/avo/blob/main/app/components/avo/fields/trix_field/show_component.html.erb), [show 2](https://github.com/avo-hq/avo/blob/main/app/components/avo/fields/trix_field/show_component.rb), similar for edit)
 - a js controller ([example](https://github.com/avo-hq/avo/blob/main/app/javascript/js/controllers/fields/trix_field_controller.js)). In order to make the JS to work you need to add the js file and register the controller [here](https://github.com/avo-hq/avo/blob/main/app/javascript/js/controllers.js)

As a database column [I see](https://stackoverflow.com/questions/8150721/which-data-type-for-latitude-and-longitude) that some use the `point` data type, but most people have two columns `latitude` and `longitude`.
We could join them into one field using a getter and setter on the model.
```ruby
class City
  def coordinates
    [latitude, longitude]
  end
  
  def coordinates=(value)
    self.latitude = value.first
    self.longitude = value.last
  end
end
```

This is my approach, but feel do your thing.

Thanks!

**Comment by yondifon** [comment]
Alright. thanks a lot @adrianthedev

**Comment by helpotters** [comment]
I'll offer up my assistance as well. @yondifon, lemme know if you want me to take on anything that help you along. 

Depending on the coordinates usage, I'd suggest looking into the following: 

- **[Numeric/Decimal](https://techtrails.io/rails-geographic-coordinates/)** datatypes (rational numbers) for each lat/long column like @adrianthedev mentioned.
- [geocoder](https://github.com/alexreisner/geocoder) may be useful 

I don't have any professional experience yet, so take my suggestions with a grain of salt. I used gps coords for a concert locator Rails app and I can say that [geocoder](https://github.com/alexreisner/geocoder) helped with simplifying coordinate operations.

**Comment by adrianthedev** [comment]
I see this very similar to the tags field. There are gems out there that bring the tagging feature out of the box, like [`acts_as_taggable_on`](https://github.com/mbleigh/acts-as-taggable-on), but some want to create that functionality themselves. So we enable that too.

The same here. If people want to use the "bare minimum experience" they can use two columns `lat&long`, that's fine.
If others want to use a full-fledged solution like `geocoder`, that's also fine. 
We have to enable the usage of both...

**Comment by helpotters** [comment]
I chatted with [@milypm](https://github.com/Milypm). We're both still in the job hunting stage of our Ruby on Rails journey and we want to collaborate on this issue. Any experience at all is a boon to our resumes/githubs and a collaboration would help us with experience working on a team. 

@yondifon, I noticed that you're currently employed as a developer. I was wondering if you'd let us take over this bounty? It'd be a big help to our job hunting opportunities.

**Comment by yondifon** [comment]
Go ahead @helpotters

**Comment by helpotters** [comment]
Thank you. We'll get started on it today.

**Comment by helpotters** [comment]
Any suggestions on how to handle two data inputs in one field? 

Here's how I'm currently implementing it for just latitude in the city editor. _sidenote: I had to define the placeholder in the editor, not the resource_

```ruby 
  <%= avo_edit_field(:location, :latitude, form: form, placeholder: "Enter latitude") %>
```

Ideally, the location field would have inputs for lat and lng. I could do some javascript to get it to work (perhaps similar to date strings), but I wanted to see if you had any suggestions or references for handling arrays and/or formatting data. 

```ruby 
<%= field_wrapper **field_wrapper_args do %>
  <%= @form.number_field @field.id,
    class: classes("w-full"),
    placeholder: @field.placeholder
  %>
  <%= @form.number_field @field.id,
    class: classes("w-full"),
    placeholder: @field.placeholder
  %>
<% end %>
```


And here's a relevant spec: 

```ruby 
    context 'edit' do
      it "has a field for latitude" do
        visit "/admin/resources/cities/#{city.id}/edit"

        latitude_element = find_field_element("latitude")

        expect(latitude_element).to have_text "LATITUDE"

        expect(find("#city_latitude", visible: false)).to have_text("")
        expect(find("#city_latitude", visible: false)[:placeholder]).to have_text("Enter latitude")
      end
    end
```

After I cover the basic inputs, I'll work on making it as robust as the time field. 

![image](https://user-images.githubusercontent.com/22648572/225167981-158ef449-08a4-48c1-a507-4f0e430bfe07.png)

**Comment by adrianthedev** [comment]
Sure @helpotters.

To do that, we should add a getter on the model.
Given that the model has `latitude` and `longitude` fields, that would look like this:

```ruby
# app/models/city.rb
def coordinates
  [latitude, longitude]
end

# app/avo/resources/city_resource.rb
field :coordinates, as: :location
```

This way, the Avo field knows that it's going to need an array with latitude as the first element and longitude as the second and will render the map like that
Does that sound good?

How do you feel about submitting the PR? It's all good if it's not finished and messy. It would help us better collaborate on code, rather than hypothetical scenarios.

**Comment by helpotters** [comment]
I apologize for the delayed response. The PR has been submitted. I'm mainly having issues with the field rendering the array input. One quirk I noticed is that the empty coordinates array will render as `[nil, nil]` rather than the empty dash `—`. 

If you have any best practices suggestions, let me know! I'll definitely be able to make the feature robust after this roadblock. Thank you for helping me out here.
