### ISSUE TITLE
Custom authorisation policy scope is not used for belongs_to association

### ISSUE THREAD

**Issue by adrienpoly** [avo-hq/avo#1521]
### Describe the bug
I have a `Universe` and a `Story` model

a story belongs_to :universe 
both model have custom policy

```ruby
class UniverseResource < Avo::BaseResource
  self.authorization_policy = Admin::UniversePolicy
  ...
end
``` 

```ruby
class StoryResource < Avo::BaseResource
  self.authorization_policy = Admin::StoryPolicy
  ...
  field :id, as: :id
  # Fields generated from the model
  field :universe, as: :belongs_to
end
``` 

The `Admin::StoryPolicy` and `Admin::UniversePolicy` are well applied for most views.

But when I visit the `edit` view of the `Story` the `universe` field options are coming from the `UniversePolicy::Scope` and not from `Admin::UniversePolicy::Scope`

<img width="941" alt="Screenshot 2023-01-10 at 13 12 55" src="https://user-images.githubusercontent.com/7847244/211548716-ab0f79ad-f96c-4879-b414-33c25b63b549.png">

### Expected behavior & Actual behavior
the scope should be coming from the custom policy

**Comment by adrienpoly** [comment]
Ok I have a partial solution for this issue. If I add `searchable: true` it does uses the correct scope

**Comment by adrianthedev** [comment]
Hey @adrienpoly. Sorry I've been away.

That's by design. As per the authorization methods, the main policy does not influence the methods or query scope when viewing the resource as an association.
The fix for that is to use the [`scope` property](https://docs.avohq.io/2.0/associations/has_many.html#add-scopes-to-associations) on the association field. You may apply the policy scope to the associated record through it.

The reasoning is to give the developer the flexibility to scope out the query however you want it in different places (Index, association, search).

**Comment by adrienpoly** [comment]
Hum I am not sure to understand. 

Here what I am seeing when `searchable` is not set (or false) : 
the story#edit page has the options of universe field coming from `UniversePolicy::Scope` values. To me for an association either no policy should be apply or the custom policy. 

What is also strange is that the beavior is not the same depending on the searchable option

**Comment by adrianthedev** [comment]
Yes. I agree.

The searchable `belongs_to` should not have the same scoping behavior as the `association`. 
The reason why that is happening is that the searchable belongs_to is actually using the search feature, so the policy scope is applied, and the non-searchable belongs_to does not use the search feature. Hence the policy scope is not being applied.

The resource and global search has the policy scope applied (so the same scope as the `Index` view) because it makes sense to have the records scoped to that user.

Does that make sense?

**Comment by adrienpoly** [comment]
> Hence the policy scope is not being applied.
But I can see that a policy is apply this is what is confusing to me

**Comment by adrianthedev** [comment]
So in what case do you see the policy being applied?

1. `field :universe, as: :belongs_to, searchable: false`
2. `field :universe, as: :belongs_to, searchable: true`

I checked on my end and only on 2 it gets applied (which is what I described)

**Comment by adrienpoly** [comment]
I have 2 policy 

UniversePolicy (for my app)
Admin::UniversePolicy (for the admin)

for 1 scope is coming from UniversePolicy 
for 2 scope is coming from Admin::UniversePolicy

**Comment by adrianthedev** [comment]
Hmm. That's weird. Let me look into it today or tomorrow. It might be that different scopes are being applied in different places.

**Comment by adrianthedev** [comment]
Ok. I fugured it out. When the `belongs_to` field fetches the associated records, it applies the authorization scope on top of `resource.class.query_scope` which itself adds the authorization scope. The difference was that the `query_scope` finds the proper authorization policy (the one declared in the resource), and the `belongs_to` field auto-figures it out, giving you the wrong one.

Thanks for sending this in 🙌

**Comment by adrienpoly** [comment]
cool thanks for fixing it
