### ISSUE TITLE
Chain of actions

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1559]
### Feature

Sometimes actions need to respond back with some crunched data.
We might be able to create some kind of chained actions that will make it look like it's a single action.
Maybe even steps for actions?

**Comment by Paul-Bob** [comment]
[`navigate_to_action`](https://docs.avohq.io/3.0/actions.html#navigate_to_action) available since 3.4.2

1. Go to https://main.avodemo.com/avo/resources/cities
2. Select at least 1 city
3. Click on update action from the actions list
4. Select attributes to update
5. Click run
6. Change values 
7. Click run

Closing as already implemented.
