### ISSUE TITLE
Date field displaying different dates on new records

### ISSUE THREAD

**Issue by estebanutz** [avo-hq/avo#1570]
### Context
The date field shows a different date when creating a new record. Locally it shows the current date, today's date. For example: Feb 6 2023, but on production, it shows January 31, 2023.
I have this resource field: `field :published_date, as: :date, required: true, sortable: true, picker_format: 'F d, Y', format: "DD", default: Date.current, placeholder: Date.current`

I checked the Date on the production server and it displays the correct date for today. Any ideas? 

### System configuration
**Avo version**: 2.15.3

**Rails version**: 6.1.7

**Ruby version**: 2.7.2p137

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
I added the same config [to the demo app](https://github.com/avo-hq/main.avodemo.com/commit/7b23631ba45a645adc05dda551411ea37c5e54c3), and the date [is displayed correctly](https://main.avodemo.com/avo/resources/users/new?avo_debug=1).

Try to declare that default option using a block `default: -> { Date.current }` rather than `default: Date.current`. The block should be evaluated on runtime, while your option might be evaluated on deploy time (maybe you deployed on January 31st?).

To debug this, try to access that new page with `?avo_debug=1` param. Then inspect the DOM below that field. You should see the raw value of that field in an HTML comment.

![CleanShot 2023-02-06 at 23 15 47](https://user-images.githubusercontent.com/1334409/217089821-7a1023b5-ef00-4cc1-813c-01d7658d5b92.gif)

**Comment by estebanutz** [comment]
@adrianthedev This `default: -> { Date.current }` fixed the "issue". Thanks!
