### ISSUE TITLE
Consistency with hashes of options

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#1578]
### Context
This is a minor issue, but which could be a nice improvement to DevX, since I've had this issue several times already. 

Let's picture a resource with a `category` column, and a frozen array of options in our model. It is pretty common to have both a `select` field, and at some point a `Filter by Category` feature. Unfortunately the current avo API to define a hash of options for `select` fields and `filters` use inverted label-value pairs:

```ruby
# Select field
field :type, as: :select, options: { 'Large container': :large, 'Medium container': :medium, 'Tiny container': :tiny }, display_with_value: true, placeholder: 'Choose the type of the container.'

# Filter options
def options
  {
    is_featured: "Featured",
    is_unfeatured: "Unfeatured"
  }
end
```

This means that I often have to `invert` stuff arbitrarily in the codebase when computing options from several places. Not the end of the world, but a bit awkward.

**Comment by adrianthedev** [comment]
I agree with you 100%.

This probably happened because I come from PHP and JS and it's customary to have the keys as the `id` and values as the `label`, but in Rails `select` forms is the other way around (which was difficult for me to grasp).

I'm thinking to keep the Rails way of doing things and support arrays `["is_featured", "is_unfeatured"]` and labels in keys just like for select fields `{ "Featured": is_featured, "Unfeatured": is_unfeatured }`.
What are your thoughts?

**Comment by bear-in-mind** [comment]
I'm fine either way, really! My personal preference goes to `id: label` (like you), but that would mean inverting things at the view level, which can be a pain if it has to be done everywhere.

As long as it's consistent, either solution is fine :)

**Comment by adrianthedev** [comment]
We'll go with the Rails `select` way of doing things `{label: id}` from now on (Avo 3 and upwards).
