### ISSUE TITLE
Sidebar resource fetching won't look into a custom policy

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#1591]
### Describe the bug
I'm using a custom policy for my `UserResource`. Unfortunately, the `index?` method being called is not the one I specified in the resource (`Avo::UserPolicy`), but the default `UserPolicy`, which has a different rule. I'll have a look into it :)

### Steps to Reproduce
1. Add a custom `authorization_class` to a resource
2. Set its `index?` to `true`
3. Go to the default policy where avo would normally look, and set `index?` to `false`
4. You'll see that the resource in the sidebar disappears

### Expected behavior & Actual behavior
The automatic lookup in each resource's `index?` method policy should take custom policies into account.

### System configuration
**Avo version**: 2.26

**Rails version**: 7

**Ruby version**: 3.1

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @bear-in-mind.
I see what you mean. I presume you're not using the menu builder feature and it's the standard generated menu (all dashboards, all resources, all custom tools).
That may happen because it will try to fetch the policy based on the model, not the resource. We should fix that.

Meanwhile, you could use the menu builder and declare each resource. On the resource declaration use the `visible` option and the `authorize` method with the `policy_class` option.

```ruby
resource :team, visible: -> {
  authorize current_user, Team, "index?", raise_exception: false, policy_class: CustomTeamPolicy
}
```

**Comment by bear-in-mind** [comment]
Hey @adrianthedev ! Yes, thanks, that's what I ended up doing. It's just that since the doc says that it takes the policy's `index` method into account, it took me a while to understand what was going on 😅
