### ISSUE TITLE
Add the ability to display full text attributes on index view

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#1600]
### Feature
Currently I have a description attribute that can be very long that I would like to make available to view in the index. One option is to allow the description to span multiple rows or the second option is to give the ability to hover over the text in order to read the field.

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/48605824/221608813-5f339816-7e44-43e0-ac22-bd8277fc39d8.jpeg)

**Comment by adrianthedev** [comment]
Some of the things you can do right now besides rolling out your own solution:

1. Add `simple_format` to the value output

In that custom field `index_component.html.erb` wrap it with `simple_format`

```erb
<%= index_field_wrapper **field_wrapper_args do %>
  <%= simple_format(@field.value) %>
<% end %>
```

<img width="1579" alt="CleanShot 2023-02-27 at 17 48 54@2x" src="https://user-images.githubusercontent.com/1334409/221611564-607d7624-e10c-4fca-bfd1-168577472ec7.png">


2. Use an Avo controller to open up a floating tooltip

```erb
<%= index_field_wrapper **field_wrapper_args do %>
  <div data-controller="tippy">
    <%= link_to "More", 'javascript:void(0);', data: { 'tippy-target': 'source' } %>
    <div class="hidden" data-tippy-target="content">
      <div class="p-2 space-y-2">
        <%= @field.value %>
      </div>
    </div>
  </div>
<% end %>
```
Be careful because this is a private controller that is subject to change. You can copy it over to your app or keep an eye on the changelog to see if it needs updating.

![CleanShot 2023-02-27 at 17 48 34](https://user-images.githubusercontent.com/1334409/221611496-7b9480f3-04a5-4b5a-a80f-a6d8305c821b.gif)

**Comment by jmarsh24** [comment]
Wow this is great! I really like the hover over option. I think this would be something great to add to long texts attributes along with an attribute to truncate the display value.

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen if this persists
