### ISSUE TITLE
Assets not Compiling in Production

### ISSUE THREAD

**Issue by ricardobucho** [avo-hq/avo#1649]
### Context
On a rails 7 app set up with jsbundling and cssbundling, all of my assets are compiled properly. Avo's on the other hand, not so much. All of the settings in the avo initializer work in development but do not get compiled when in a production environment through the assets:precompile command.

I've tried using the gem directly from rubygems as well as from github + manual compiling and my settings are never applied. Not entirely sure what I can be missing here. Let me know if there's any other info I can provide.

Gemfile
```ruby
...

gem "rails", "~> 7.0"
gem "sprockets-rails", require: "sprockets/railtie"

gem "cssbundling-rails", "~> 1.1"
gem "jsbundling-rails", "~> 1.1"
gem "turbo-rails", "~> 1.1"

...
```

Compile Commands
```json
"scripts": {
  "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules",
  "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets"
},
```

### System configuration
**Avo version**: 2.28.0
**Rails version**: 7.0.4.3
**Ruby version**: 3.2.1

**License type**
 - [X] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [X] No

**Comment by adrianthedev** [comment]
Thanks for opening up the ticket.

The first thing that comes to mind is that the gem is made to be used through rubygems, not by cloning the repo. That's by design, not by flaw. We can automate much of the asset compiling so your app does not have to compile anything for Avo when you deploy. This leads to faster deeply times and fewer dependencies for you.
[This](https://avohq.io/blog/how-to-bundle-assets-in-a-rails-engine) is an article we wrote about that.

Form what I can see in this ticket, Avo's assets should show up fine when used from rubygems.org. Not sure what the problem is.

Now, the easiest way for me to test that out is if I had a repository ready for me to try out. Seeing how you already have all the context, could you please set it up and give me a link to clone it?
Thank you!

**Comment by ricardobucho** [comment]
Hey @adrianthedev, I've added you to the repo. Feel free to pull it. It's unfinished work so I didn't wanna make it public yet.

**Comment by adrianthedev** [comment]
Hey @ricardobucho can you try replacing `gem "avo", github: "avo-hq/avo"` with `gem "avo"`?
That fixed the assets for me in development.
I'm curious if that will fix it in production too.

**Comment by ricardobucho** [comment]
Oh, I had that before @adrianthedev. It worked in development like you said but in production would do the same thing. Using github was my latest attempt at trying to fix it.

**Comment by adrianthedev** [comment]
<img width="751" alt="CleanShot 2023-03-27 at 14 21 50@2x" src="https://user-images.githubusercontent.com/1334409/227927703-79a826ca-d643-4da4-a56e-db50d21170d9.png">

BTW, there are steps to have the app installed from GitHub in the docs on the installation page.

**Comment by ricardobucho** [comment]
Checked everything @adrianthedev, all looks good. No network errors, everything is a 200. Just to be clear, it's not that the assets aren't all working. It's the custom stuff on the `config/initializers/avo.rb` that I've set that are not getting used in the production environment. And it's not just the images. The colors aren't either. As for the Rakefile stuff, I did that too when pointing the gem to Github.

**Comment by adrianthedev** [comment]
> all of my assets are compiled properly. Avo's on the other hand, not so much.

From this I thought that the assets are not loading in production, that's why I went that way.

So "nothing in the initializer", what does that mean? Because if that path that you're using is not `avo` (as specified in the initializer), then it means that some things are getting used.

The branding is not working on your end because the branding feature is a a part of the Pro license. On the documentation, that's specified on the top of the page.

<img width="827" alt="CleanShot 2023-03-27 at 14 42 37@2x" src="https://user-images.githubusercontent.com/1334409/227932113-ace22dc5-f35c-4d2a-a2e6-e575b4dd299a.png">

You can see more of the Pro features [here](https://avohq.io/pricing). You can use that page to purchase a license too.

Outside the branding feature, is there anything else that's not working that I should look at?

**Comment by ricardobucho** [comment]
Oh! I completely missed that... problem solved then. My other version was lower than 2.15 that's why everything was still working so I was just confused. Sorry for taking your time and thanks for all the help @adrianthedev!

**Comment by adrianthedev** [comment]
No worries! I'm glad it all worked out.
