### ISSUE TITLE
Allow resource menu items to receive params

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1651]
### Feature

From [this discussion](https://discord.com/channels/740892036978442260/740893011994738751/1090017637079207946).

We'd love it if the `resource` menu items would receive the `params` option, which would be a `Hash`, and that would be appended to the generated URL.

```ruby
resource :clients, label: "Active", params: {
  filters: "THE_FILTER_QUERY"
}
```

As a block
```ruby

        resource :projects, params: -> {
          params = {}

          if current_user.is_admin?
            params[:foo] = :bar
          end

          params
        }
```

### Current workarounds

One can use a `link_to` operator.

```ruby
link_to "Active", "/avo/resource/clients?filters=THE_FILTER_QUERY"
```

**Comment by bryszard** [comment]
Hello @adrianthedev, I have created a POC for this feature, but I will need some advice about:
1. Telling if it's the right direction that I took
1. Deciding what to do with the `active_link_to` problem

I explain it in [my PR here](https://github.com/bryszard/avo/pull/1) (didn't set the main repo as the target, because it's POC).

**Comment by Paul-Bob** [comment]
> Additionally, I have a doubt if your intention is to allow also using the `block` for `:params`. I'm not sure, because you're only saying that it's a workaround right now.

Hi @bryszard I let you a detailed review on the PR.
I edited the issue, the intention is to allow a lambda syntax on the `params` argument. It was wrongly on the workaround section.
