### ISSUE TITLE
creating resources with linked resources and conditional visibility will not work anymore

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1711]
### Context
The database structure is the following

1. Assignment
2. Objective

An Assignment has many Objectives, an Objective belongs to an Assignment

assignment_resource.rb
```ruby
...
field :objectives, as: :has_many, visible: -> (resource:) { resource.model.enabled? }
...
```
When viewing or updating an assignment, it works as expected and the associated objectives are displayed if the assignment is `enabled`. However, when creating a new assignment, an error occurs: `undefined method enabled? for nil:NilClass`, because the resource is not yet created and the corresponding `model` instance is not available.

**This also apply to files (active record) - not only has_many relations**

We are not sure after which version this error occurs, but it has worked before at some point.

### System configuration
**Avo version**: 2.30.2

**Rails version**:7.0.4.3

**Ruby version**:3.2.0

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/26464774/234246741-aa24c3b1-966a-4918-bf6d-5b55f03e2b01.png)

**Comment by Paul-Bob** [comment]
Hi @FLX-0x00, after [this security update](https://github.com/avo-hq/avo/pull/1694) we're running the visible blocks on new / updates. Therefore, it is important to ensure that the visible block can be executed even when the record has not been created yet.

To protect against this situation, there are several possibilities. I am unsure of your use case, but here are some examples that may help you achieve the desired results:

Examples:
`visible: -> (resource:) { resource.model&.enabled? }`
OR
`visible: -> (resource:) { resource.model.present? ? false : resource.model.enabled? }`
OR
`visible: -> (resource:) { resource.model.present? ? true : resource.model.enabled? }`

Please let us know if you have any questions.

**Comment by adrianthedev** [comment]
Yeah. I see the breaking change too.

**Comment by FLX-0x00** [comment]
The hotfix provided by @Paul-Bob works but i also think this is not the best / smoothest solution. Thanks anyway to provide a hotfix

**Comment by Paul-Bob** [comment]
### Context

From [this comment](https://github.com/avo-hq/avo/issues/1685#issuecomment-1510418561), a [security issue](https://github.com/avo-hq/avo/issues/1695) was discovered. @FLX-0x00 discovered that fields that are not visible can still be updated. To address this issue, we implemented [this security update](https://github.com/avo-hq/avo/pull/1694).

### Fix

The security update mentioned above adds a visibility check that marks fields as NON-Updatable if the visible value/block returns false.

### Problem

The visibility check on create/edit is executed to determine whether the field is updatable or not before assigning the params to the model, the model is nill on that evaluation, that's why you're experiencing this issue.

### Solutions

We are still evaluating several approaches.

One of them is to leave it as is and have each user protect against nil values on the model, although we know this is not ideal.
`visible -> (resource: ) { resource.model } # resource.model is nil`

Another approach could be to pass an instance of the model without any assigned params, which would mean that all attributes would be filled with nils/defaults.
`visible -> (resource: ) { resource.model } # resource.model is #<ModelClass:0x00007f7df4d92000 id: nil, name: nil, status: "default">`

We are open to suggestions on how to approach this issue.

**Comment by FLX-0x00** [comment]
I think an empty instance of an object should be the best option to keep the code clean and maintainable. All methods available on a real instance are available on an "empty" or "new" instance, so nothing should break. Only then is creating an instance and perhaps providing a dummy object the cleanest solution for users. Maybe the visible options should be evaluated after the `new` method called where an empty variable is availabe if that makes sense...

**Comment by Paul-Bob** [comment]
My only concern about the "empty" / "new" instance is that the visible block is evaluated on wrong data leading to another security breach... 

> Maybe the visible options should be evaluated after the new method called where an empty variable is availabe if that makes sense...

The visible options normally are evaluated when a model variable it's already present. The only moment where visible block run before a model is present is when we try to figure out witch fields are or not updatable in order to create the model, that happens on form submissions, create / update

**Comment by FLX-0x00** [comment]
But it only affects the has_many associations. The fields are validated correctly, but the has_many and the files are not. These associations are not relevant when creating a resource. only when belongs_to is used.

**Comment by FLX-0x00** [comment]
okay, nevermind, was at the wrong spot
