### ISSUE TITLE
Confusing state when search? is not defined in the Policy 

### ISSUE THREAD

**Issue by adrienpoly** [avo-hq/avo#1750]
### Describe the bug
I was in a situation where my global search cmd+k would return results but my resource search (the search bar above the index) won't return anything.

After a bit of investigation I discovered that I need to have a `search?` method in my policy. Once this was set then all worked perfectly.

### Steps to Reproduce
1. Use Pundit authorization layer
2. don't add a search? method to the base policy
3. test resource search and global search

### Expected behavior & Actual behavior

It was a bit frustrating to see results in one field and not the other.
My recommendation would be to either : 
1. have a consistent behaviour : if the search? method is not available then both search field don't return anything
2. if the search? method is false then hide the resource search field

I think my preferred solution would be a combination of both
If for a user the search is set to false in the policy then the resource search should not be visible and the search results should not be visible 

Digging a bit into the code it looks like in the global search 
For this line we have `policy_class` being nil 

```ruby
# avo/services/authorization_service.rb
authorize(user, record, action, policy_class: policy_class, **args)
```
and therefore it always returns true

when doing a a resource search the `policy_class` is correctly set

**screenshot**
<img width="1284" alt="Screenshot 2023-05-16 at 12 29 16" src="https://github.com/avo-hq/avo/assets/7847244/28bef027-8a0c-47d6-bac0-4a2a41d9fdff">

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
Yes, I agree. Avo should take the `search?` action into account for global search too.

We'd merge a PR if we had one 🤞

I added a warning on top of the page. There is a more detailed section lower.
<img width="745" alt="CleanShot 2023-05-17 at 18 48 29@2x" src="https://github.com/avo-hq/avo/assets/1334409/e0fb79d0-c1d1-4cf4-bc8f-d125a889e9cc">

**Comment by adrianthedev** [comment]
I tested this and it seems that with the `search?` method, it works fine.

It's an unfortunate bug that it doesn't work the same without the `search` method because of how Avo gracefully accepts not authorization by default. So, instead of returning `false` when no method is found, it returns `true` because it gracefully allows you to use Avo without authorization.
I have pondered the idea of having it the other way around, but that's a discussion for another time. We'll probably introduce that feature at some point.

I think the best resolution here is to add a `search?` method that returns `false`. You can also customize it using [different method names](https://docs.avohq.io/2.0/authorization.html#using-different-policy-methods).
