### ISSUE TITLE
The name passed to fields is not applied on validation errors

### ISSUE THREAD

**Issue by lukasedw** [avo-hq/avo#1794]
### Describe the bug
I am passing the names to fields like this:

``` ruby
field :name, as: :text, name: _("Name")
```
I am using an auto-translate service.
But on validation, is shows the name of the field.

![image](https://github.com/avo-hq/avo/assets/13969616/5ad65f81-22fe-4b24-8e29-29e1231bfc96)

### Steps to Reproduce
1. Create a field and give a custom name
2. Create a validation for it
3. Trigger the error and see that is not the name of the field on validation error message.

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by lukasedw** [comment]
Also, something that I noticed on the production build. The name fields don't change.

![image](https://github.com/avo-hq/avo/assets/13969616/8a3f9a80-4f2e-4557-b5be-d88d9a8dbb35)

![image](https://github.com/avo-hq/avo/assets/13969616/1c042f40-9eb3-4a06-83d9-0f464b6f0853)

**Comment by lukasedw** [comment]
This is the product that I am using: 

https://translation.io/rails
https://github.com/translation/rails

**Comment by adrianthedev** [comment]
That's probably not going to work as expected, and I'll try to explain why.

Because the `field` method is a class method and it's getting evaluated on Rails boot time, the  `name` option is also evaluated on boot time. At that point `I18n` does not have it's translation files loaded, and I assume that translation.io doesn't either.
One way of doing that would be to pass it a block which can be evaluated on runtime (when the library has the translations loaded). The `name` option doesn't support blocks, but that might be added using a PR.

Now, even if you pass the `name` as a block, that would still not count for validations and other places. Avo's pretty tightly integrated with the default I18n library.

The change should be done within the `BaseResource.name` and `Baseresource.plural_name` in one of two ways:

1. We would be open to a PR to support `_()` first class if you would submit one.
2. I think that you could monkey-patch it to not use `I18n` but use your implementation.

So, yeah, I know it's not very plug-and-play, but we'd love some help in making it better.
