### ISSUE TITLE
resources inside tabs are not checked against the index? policy

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1812]
### Context
Consider a has_may relationship, for example, Accounts has many roles and you want to display this in the Account resource.

```ruby
field :roles, as: :has_many
```
Before a simple panel will be visible, avo checks the `index?` policy for roles if you are using pundit or something else. If `index?` is `false`, the panel will not be rendered.

In tab view the pill is rendered and results in a `content missing` message or show loading screen if it is the first item. It would be nice if a resource inside a tab would also be checked against the `index?` policy and the corresponding tab would not be visible.

```ruby
  tabs style: :pills do
    field :roles, as: :has_many
  end
```
```ruby
class RolePolicy < ApplicationPolicy
  def index?
    false
  end
end
```
![image](https://github.com/avo-hq/avo/assets/26464774/e7114906-dca9-4b35-a265-da7764705392)

**Comment by Paul-Bob** [comment]
Hello @FLX-0x00 this issue is fixed on a PR and will be merged soon. By your example the roles will not be checked. In order to check the `index?` on roles you should use `inherit_association_from_policy` helper inside `Account` policy or manually define the `view_roles?` method. 

Anyway I managed to reproduce the described error even if the example code is not 100% correct, I just want to reassure that you'll use the correct way after this is fixed.

**Comment by FLX-0x00** [comment]
We already use the inherit_association_from_policy. I forgot to mention this. I will check the code later that day. Thanks man!
