### ISSUE TITLE
Generate an `Avo::BaseResourcesController` from which all controllers inherit

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1822]
We'd like to generate by default a base resources controller so users can override methods globally for all resources.

- It should not be named `ResourcesController` because there was a case where one user had the `Resource` model in their app.
- the resource generator should check for this base resource and if it doesn't exist it should create it

Related ticket https://github.com/avo-hq/avo/issues/1758.

**Comment by Paul-Bob** [comment]
I propose an alternative approach.

Instead of enforcing a specific naming convention for controllers, we can empower the developer to choose their own controller name. We can introduce a configuration option in the initializer, allowing the developer to explicitly specify the base class that all controllers should inherit from.

This approach offers flexibility and customization. The key advantage is that we no longer need to be concerned about potential conflicts arising from the project having a resource with the same name as a controller we create. It becomes the developer's responsibility to handle such scenarios.

What do you think @adrianthedev ?

**Comment by adrianthedev** [comment]
I know, but then we have another configuration key to maintain and they have to rename the controller when they change that setting.
Also we need to make some kind of dynamic call everytime we reference that controller.

I would stick to having a static option and that's that. If they want to rename it, that's still possible and it's on them to do it.

**Comment by adrianthedev** [comment]
Here's how View_component does it
