### ISSUE TITLE
'files' type not handled on actions

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1868]
### Describe the bug
The field "files" is not handled in an action, it is displayed as label.

### Steps to Reproduce

Create an action: 
```ruby
class AssetsUploadAction < Avo::BaseAction
  self.name = 'Upload Assets'
  self.standalone = true
  self.visible = -> { view == :index && !parent_resource.nil? }
  self.message = 'Import several assets at once'

  field :assets, as: :files
```

### System configuration
**Avo version**:
2.7.2

**Rails version**:
7.0.6

**Ruby version**:
3.2.2

**License type**:
 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

![image](https://github.com/avo-hq/avo/assets/201689/fa721cf3-e2db-41fe-80b1-dd965457aeff)

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
This is happening because the authorization stops the field from getting rendered.

**Comment by jetienne** [comment]
Is this something to do on my side?

**Comment by adrianthedev** [comment]
Sorry. I didn't complete my sentence. No. it's something we have to fix and release in the next few days.

**Comment by jetienne** [comment]
@adrianthedev No problem. This will be part of the maintenance release tomorrow ?

**Comment by adrianthedev** [comment]
Releases are usually [on Tuesday](https://github.com/avo-hq/avo/blob/main/RELEASE.MD). I'm waiting for @Paul-Bob to finish up on some personal work and get to it. It shouldn't be very difficult to fix.
We'll cut an intermediary release as soon as it's fixed.

**Comment by Paul-Bob** [comment]
Hello @jetienne. 

The files fields utilize authorization to offer precise control over actions such as upload, download, and destroy. 

At first glance, this level of authorization might seem unnecessary for actions, leading to the perception of an issue or bug. 

However, if we examine it from another perspective, we can understand that when an action is loaded from a record's show page, the files field on that action can be populated with the specific files related to that record. As a result, users can perform actions on those files.

Considering this scenario, we view this issue not as a bug, but rather as an "edge case" that hasn't been extensively documented. 

We are working on enhancing the documentation to provide better clarity.

In order to fix it ensure that the resource's policy, where the action is being executed has the `upload_assets?` method defined and returning true. Let me know if you still have questions.

https://docs.avohq.io/2.0/fields/files.html#authorization

**Comment by jetienne** [comment]
works :)
