### ISSUE TITLE
Couldn't find template for digesting: /avo/index/resource_table_component"

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1870]
### Describe the bug
A minor issue : my log shows this error:

```json
{
    "app_name": "app",
    "dt": "2023-07-27T16:43:50.917623Z",
    "host": "host",
    "message": "E, [2023-07-27T16:43:50.917553 #2] ERROR -- : [1d594457-6d2c-4f25-9ab2-070aefc8b680]   Couldn't find template for digesting: /avo/index/resource_table_component",
    "platform": "Heroku",
    "proc_id": "web.1",
    "source_type": "heroku_logs"
}
```

### System configuration
**Avo version**:
2.37.2

**Rails version**:
7.0.6

**Ruby version**:
3.2.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hmmm. I have never seen this messge before `Couldn't find template for digesting`. Is that a Rails thing? Can you reproduce it by doing something and getting a 500 back?

I googled it for a bit but can't seem to put my finger on what the issue is.
It's the first time I've seen anyone reporting this.

Unrelated to that, what are you using for logging? I presume that's a production log entry. How is it formatted like that (as a hash)?

**Comment by thubamamba** [comment]
I am wondering if this can be reopened? I am facing a similar issue on render.com

**Comment by Paul-Bob** [comment]
@jetienne did you fix it?
