### ISSUE TITLE
Please configure the 'inverse_of' option for the 'has_many :xxxx' association on the 'zzzz' model.

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1873]
### Context
After upgrading to latest avo2 version (i think one minor or two jump) we are facing some errors of code that worked before. Have we missing some upgrade notes?

Imagine two Models "Account" and "Product". A Product has_many Accounts and an Account has_many Products. With that beeing said rails will create the account_products table and you can specify this in avo resource with:

```ruby
AccountResource ...

field :products, as: :has_many, through: :account_products
```
The problem is the `Please configure the 'inverse_of' option for the 'has_many :products' association on the 'Account' model.` message that now appears and the products has many field will not load any more on the accounts view.

### System configuration
**Avo version**: v2.37.2

**Rails version**: 7.0

**Ruby version**: 3.1.1

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No
 - [x] Yes, but not relevant parts ;)

**Comment by adrianthedev** [comment]
@Paul-Bob can you have a look at this next please?

**Comment by FLX-0x00** [comment]
Would be nice as this breaks currently our prod environment. We are not able to attach items to a resource if one is set at minimum. If it's empty the first attachment will work. After that the view does not render.

**Comment by adrianthedev** [comment]
Definitely not ok. We'll look to see if we can hotfix it quick. If not we'll revert that change and cut a release until we figure out a more permanent solution.

**Comment by FLX-0x00** [comment]
Okay, I was not sure if you are able to replicate the bug with this information. If you need more input just dm me on discord. Meanwhile we will do a downgrade of avo.

**Comment by Paul-Bob** [comment]
Hey @FLX-0x00. 

We merge this [PR](https://github.com/avo-hq/avo/pull/1856) that incorporates a check for associations in order to display the detach button. To verify these associations, we require the use of reflection. If, for any reason, the reflection cannot be obtained, we have implemented an informative error to be raised.

I think the `Please configure the 'inverse_of' option for the 'has_many :products' association on the 'Account' model.` message is quite clear but maybe not enough (any suggestions to make it more clear?). You need to go to your `Account` model (`account.rb`) and configure the [`inverse_of`](https://guides.rubyonrails.org/association_basics.html#bi-directional-associations) option on the `has_many :products` association. This step may be executed for other associations if applies.

We apologize for any disruptions caused in production.

**Comment by Paul-Bob** [comment]
> Have we missing some upgrade notes?

No, we haven't merged the upgrade notes.

I just did a [PR](https://github.com/avo-hq/avodocs/pull/71) with them now.

**Comment by FLX-0x00** [comment]
Can you provide more information about the inverse_of thing? I think I have not noticed this in our development with rails at anytime.

**Comment by FLX-0x00** [comment]
has many and belongs to are set in the models...and it worked in the last release without any changes. We used some "through" statement but I think this is not the root cause of the problem.

**Comment by Paul-Bob** [comment]
In this example, we have two models: `User` and `Item`.

`User` model has a one-to-many association with the `Item` model.
```ruby
class User < ApplicationRecord
  has_many :items
end
```

`Item` model belongs to a `User`.
```ruby
class Item < ApplicationRecord
  belongs_to :customer, class_name: "User"
end
```

Now let's say we have configured our `UserResource` with the `field :items, as: :has_many`.

When we render the `items` field on the `UserResource`, we need to check the inverse of the `items` association.
To do this, we use Rails' `inverse_of` method. However, sometimes this method can't figure out the inverse association and returns `nil`.

In those cases, we raise an error (which will become a warning after the pull request at https://github.com/avo-hq/avo/pull/1874) informing that we couldn't get the `inverse_of` and asking for configuration.

For example, the error message could be: `Please configure the 'inverse_of' option for the 'has_many :items' association on the 'User' model.`

To fix this, we need to go to our `User` model and configure it like this:

```ruby
class User < ApplicationRecord
  has_many :items, inverse_of: :customer # because the other end of the association is `belongs_to :customer, class_name: "User"` (on `Item` model)
end
```

This verification was introduced in Avo version `2.37.1` that's why you're experiencing this error only after the update.

Why is this necessary?

In the given example, the `Item` should always belong to a `User` because there is no `optional: true` option. If we can't figure out the `inverse_of`, we will render the detach button by default, which will not work as expected since the association should always exist.

**Comment by jayzz55** [comment]
Thank you @Paul-Bob and @adrianthedev for the quick fix on this issue 🙇
