### ISSUE TITLE
Enum filter not working properly

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1894]
The Dynamic filter for a select field does not work on dynamic search.

**Comment by Paul-Bob** [comment]
@adrianthedev It looks fine to me. At first I think something is wrong because in some resources it was working and other not. I noticed that in the resources that was not working we missed `ransackable_attributes` on the attribute, for example, `Course` `ransackable_attributes` was declared but not including `country` and `city` so the search don't raise any error just don´t work on `country` and `city`.

**Comment by Paul-Bob** [comment]
Please let me know if still noticing some weird behavior and assure that isn't because missing `ransackable_attributes`

**Comment by adrianthedev** [comment]
I did notice that the label is not displayed when using an enum
https://github.com/avo-hq/avo-3/issues/375

**Comment by adrianthedev** [comment]
Closing in favor of https://github.com/avo-hq/avo-3/issues/375
