### ISSUE TITLE
belongs_to placeholder font color is misleading

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1899]
### Describe the bug

The font color of the placeholder in the `belongs_to` fields is different from the other fields, giving the impression that a value is already set, which can be confusing for the user.

### System configuration
**Avo version**:
    avo (3.0.1.beta5)

**Rails version**:
7.0.7

**Ruby version**:
3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [ ] Advanced

### Screenshots or screen recordings
![Screenshot 2023-08-12 at 09 56 07](https://github.com/avo-hq/avo/assets/201689/ea708206-d1ad-4da4-b206-fd8b06ebdb01)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by jetienne** [comment]
@Paul-Bob When you close an issue, does it mean it's done and will be part of the next release?

**Comment by Paul-Bob** [comment]
@jetienne it depends, for example this issue was "closed this as completed in https://github.com/avo-hq/avo-pro/pull/39" That means that this issue was mentioned on that specific PR and the PR was merged. So yes, in this case it's done and will be part of the next release.

Some other issues are closed by some other many reasons, normally we always specify the reason to close the issue.

**Comment by adrianthedev** [comment]
Most closed issues will point toward the PR that fixed it. This one points to the `avo-pro` repo and probably that isn't visible.
