### ISSUE TITLE
Investigate why `view` and other vars aren't available in the `fields` method

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1916]
One of the points of having the `def fields` method was to be able to have better access to the request variables (`view`, `user`, etc.).

For some reason they are not available. I think the `def fields` method is run multiple times.
We should investigate.

**Comment by Paul-Bob** [comment]
While doing the https://github.com/avo-hq/avo-3/issues/326 I noticed that request variables, mostly the `view` is not always present. 

When a resource is initialized the `detect_fields` method is called, witch will call the `fields` method. I noticed that we sometimes initialize resources with missing params. Example: `resource.new record: record` this initialization will have `view == nil`

This last example will fetch the fields only with the record variable setted.

The `def fields` feature is great but it's really unpolished.

I also noticed that sometimes we need to get some specific field indifferently of the view, record etc... Before the `def fields` method we had all the fields always registered on the resource, now, according to the variables we can or cannot reach that specific field.

We already mentioned some possible fixes but I think we should break this task on the follow sub-tasks:

- [ ] Remove `nil` default from resource `initialize` arguments.
- [ ] Make sure that when a resource is initialized all the argument have the correct value
  - For example, when rendering a has_many, the parent resource on the associations controller have the view setted to `index` instead the real view (`show` or `edit`)
- [ ] Make `detect_fields` optional on the resource initializer (sometimes we need a resource but not it's fields)
- [ ] (NOT SURE ABOUT THIS ONE, BUT I THINK IT CAN BE USEFUL SOMETIMES) Find a way to have access to all the fields declared on the resource, indifferently of the `view`, `record` etc
  - This one can be tricky or even not doable with `def fields` API and **maybe** is not necessary if we assure that the `view` and the other arguments are always correct when initializing a resource.
- [ ] Assure that the `fields` method runs only once and cache it on each request.

**Comment by Paul-Bob** [comment]
While implementing https://github.com/avo-hq/avo-3/pull/392 I noticed a weird behavior on the City resource. After some debugging I found out that in order to edit the city name, or any other field that is on the city editor tool, we need to have that fields declared on the `form_fields` with the option: `hide_on: :forms`. It is necessary because when submitting the form we need to manipulate that "hidden"(actually never rendered) fields in order to fill the record with the params. Even if `def fields` is a powerful feature I notice more and more that we sometimes need fields from resource that are not visible and there is a big difference between:

```ruby
def fields
  # Example 1
  field :some_id, as: :text, visible: view.display?
end
```

```ruby
def fields
  # Example 2
  if view.display?
    field :some_id, as: :text
  end
```

The big difference is that in `Example 1` we are able to **always** fetch the field and execute some logic on it if necessary but on `Example 2` we only can fetch that field when on a `display` view...

I'm starting to have second toughs about `def fields` API. Again it's very powerful and UX friendly but most of our architecture it's based on **always having all fields registered on the resource.**

**Comment by Paul-Bob** [comment]
Just to clear things up. The problem is not on the `def fields` itself, its on using `if`s instead of visible block... And the whole concept of `def fields` is to make the use of `if`s possible
