### ISSUE TITLE
does the `self.visible` on action prevent bad actors to run the action

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#1989]
![Image](https://github.com/avo-hq/avo/assets/1334409/8f0b3812-9d20-4dfb-bea8-bea0c691fd18)

Also please add some docs on the `authorization` section.

**Comment by Paul-Bob** [comment]
@adrianthedev IMHO the `visible` block is to show / hide the action on the list of actions and not to prevent it from running. We can have a hidden action with a link to run it somewhere and it's a valid use case IMO. For example we can have a multiple actions flux scenario, where we go through 3 actions but we want only the entry point action to be visible.

To prevent bad actors runining the action there is the `act_on?` method or define an guard authorization per action on handle.

```ruby
  def handle(**args)
    error "Unauthorized!" and return unless args[:current_user].is_admin?

    ...
  end
```


We have some possibilities here:

1 - Visible start to control UI / Authorization (not ideal since we can want hidden but runnable actions)
2 - Add another block to action `self.authorization`
3 - Just use the handle method to return if user is not authorized

Personally I prefer option 3

**Comment by adrianthedev** [comment]
I see what you mean with 1.

I wouldn't do 3. just because our users are used to do authorization in so many ways (through policies, `show_on/hide_on` methods, `self.visible`, and more), but the thing is that they are used to do it through a DSL.
Us telling them to use 3. almost nullifies all other options.

It would be nice to do it through policies somehow.

I'd lean towards 2. but I'm sure people won't know about it and try to use `self.visible` to authorize an action, and that's ok. we need to surface the info better.

So let's do 2. please
