### ISSUE TITLE
Infinite redirect

### ISSUE THREAD

**Issue by yashka713** [avo-hq/avo#2006]
### Steps to Reproduce
1. Login using Devise
2. After successful login AVO should redirect to the `home_path` but instead it stuck in the loop

<img width="1006" alt="Screenshot 2023-10-31 at 12 45 08" src="https://github.com/avo-hq/avo/assets/15985355/90fd30a4-f8c8-45e2-84c9-97087c59d198">

### Expected behavior & Actual behavior
Redirect to `home_path`

### Models and resource files
User

### System configuration
**Avo version**: 2.41.0

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x ] No

### Screenshots or screen recordings

<img width="1006" alt="Screenshot 2023-10-31 at 12 45 08" src="https://github.com/avo-hq/avo/assets/15985355/90fd30a4-f8c8-45e2-84c9-97087c59d198">

### Additional context

Before I got this issue I am trying to upgrade my version from 2.41 to > 3
But I fully clean Gemset and re-build my Gems from scratch.

#### Impact

 - [ x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by yashka713** [comment]
Before my company purchased `pro` license I got a license error

I sent `community` in the payload, but got `pro` in the response

The error described above is related to the `Policy`, so it would be good to explain it in the log, maybe for development Env Because I spent around 4 hours trying to find why the code stacked in the infinite redirect without reason

**Comment by yashka713** [comment]
Issue with Policy after migration from `community` to `pro` version

**Comment by adrianthedev** [comment]
Hey @yashka713. Sorry for the mishap.
I'm glad you got it working.

I understand the frustration, and I hate wasting time like that, too.
I was thinking a bit on how to solve this.

In Avo 3, we removed the `self.license = "community|pro"` setting as the licensing is a bit different.
So that won't happen again like that.

Regarding authorization "getting in the way", I don't know how to fix that. I mean, we either display a warning message, or we don't. We currently don't do it.
If we were to display a warning, that warning would be triggered everytime and that might be off for when you actually use the authorization feature.

Again, I know it's frustrating, and I'm sorry for that.
