### ISSUE TITLE
Sidebar menu item hidden on safari mobile

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2009]
### Describe the bug

The mobile version of the sidebar has the profile menu item hidden on mobile safari.
We probably should use the new `vh` units or something similar and not `height: 100%`.

### System configuration
**Avo version**: All

**Rails version**: All

**Ruby version**: All

**License type**:

 - [x] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

![Dashy — Avodemo7](https://github.com/avo-hq/avo/assets/1334409/5e1c2cc9-fc8f-4d9b-b4c2-9091e975b4c8)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by sigra** [comment]
I'd to bump this issue, because I have experienced the same issue with Google Chrome mobile as well.

Look at the first screen when address bar is opened -- username and logout link are hidden. But if I scroll down a little, the browser address tab disappears and user's is visible again (second screen).

So, using this style `height: calc(100vh-4rem)` browser calculates the address bar's height into the viewport height. The workaround for this is to use `dvh` instead of `vh` which considers the state of these browser dynamic toolbars.

![Image](https://github.com/user-attachments/assets/3d7cb548-5ce4-4136-9d2e-bed33aef7811)
![Image](https://github.com/user-attachments/assets/cc5077c9-87d9-40df-88b5-7823009bd081)

**Comment by adrianthedev** [comment]
Hey @sigra.
Thanks for taking a look at this.
Would you be able to send in a PR with this fix?
