### ISSUE TITLE
Convert `via_relation_class` to `via_relation_resource`

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2156]
This is the same with `via_model` vs `via_resource`. We need to identify the resource form where we can pull the model class and not vice-versa.

I found this having an impact on `Avo::BaseComponent.association_resource`.

**Comment by Paul-Bob** [comment]
`via_relation_class` param carries a model class: https://github.com/avo-hq/avo/blob/main/app/components/avo/fields/has_one_field/show_component.rb#L49

Renaming it to `via_relation_resource` may sound like it refers to an Avo::Resource which is not

**Comment by adrianthedev** [comment]
The reasoning behind this is that in some places we use the model class in params to pinpoint the association, and we fail to capture the actual resource. The user might use a different resource than the one that Avo expects.

Ex:
Instead of User model -> User resource
The user uses User model -> AdminUser resource

**Comment by Paul-Bob** [comment]
Closing for now.

For more context:

In some cases, when making a request, both the model class and the resource need to be sent. This is because a model may use multiple resources, or a resource may be shared by multiple models.

> I found this having an impact on `Avo::BaseComponent.association_resource`.

Some issues related to `Avo::BaseComponent.association_resource` have already been resolved over the past few months.

We can revisit this if we encounter a clear issue or edge case in the future.
