### ISSUE TITLE
Suggestion/Idea: Add counter indicator on tabs

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#2254]
It would be nice to have an option to add a count (all available resources on that tab) as a badge to the tab indicator to let users know when it makes sense to click on a particular tab.

![image](https://github.com/avo-hq/avo/assets/26464774/bc50c41d-4ae8-451a-8f9d-84b18fbc359e)

like a bootstrap badge (maybe there is something similar in Tailwind)

![image](https://github.com/avo-hq/avo/assets/26464774/f30f10ae-c25b-42ed-bbef-279c64270b0a)

**Comment by Paul-Bob** [comment]
I think it can be tricky to compute this "magic number", here are two reasons why:
- Each tab lazy loads
- Each tab can have several fields, do we want the counter only on tabs that have specifically 1 `field :something, as: :has_many`?


WDYT about something like:

```ruby
tabs do
  tab "name", floating_info: -> { Users.count } do
    panel do
      fields_here
    end
  end
end
```

We can give access to `parent_resource`, `params`, `current_user` and more inside that Proc.

Open to naming suggestions since `floating_info` is not very inspire.

**Comment by adrianthedev** [comment]
I haven't played around with the actual code, so I don't know how complex it would be to add an automatic count for the association.

We could add the `floating_info` to it but I think computing that number based on the association might be difficult for the user.
In your example, `User.count` should actually be `parent_record.users.count` or something. It gets more wild if the `scope` option is used on the association.

But I do see the advantages of having a `floating_info` bubble out these where we style it beautifully and the user just passes a number to it.

Otherwise, I would suggest to do what we did lately to scopes and make the `name` callable and enable the user to [add the count](https://docs.avohq.io/3.0/recipes/display-scope-record-count.html) in the name.

**Comment by Paul-Bob** [comment]
> Otherwise, I would suggest to do what we did lately to scopes and make the name callable and enable the user to [add the count](https://docs.avohq.io/3.0/recipes/display-scope-record-count.html) in the name.

That can already be done:

```ruby
tabs do
  tab "Teams (#{record&.teams&.count}) and People (#{record&.people&.count })" do
    field :teams, as: :has_and_belongs_to_many
    field :people, as: :has_many
  end
end
```
![image](https://github.com/avo-hq/avo/assets/69730720/a0c70170-85a2-4433-99a9-3e3705ec8666)

> I haven't played around with the actual code, so I don't know how complex it would be to add an automatic count for the association.

It would not be that complex when a tab have only one field that is an association, but a tab can have none association fields or even 2 like in the example above, that's why I think the user should be in control to do the own logic inside the "`floating_info`" (it can even be text like "99+")

**Comment by FLX-0x00** [comment]
Perfect solution. The floating element is not mandatory.. I love the simple solution with the string interpolation, so that we can see the amount right on one screen without clicking! Thanks 👍

Maybe something you want to add to the docs ;)

**Comment by Paul-Bob** [comment]
Cool! https://github.com/avo-hq/avodocs/pull/156 we're adding a recipe ;)
