### ISSUE TITLE
Ruby on Jets

### ISSUE THREAD

**Issue by djolereject** [avo-hq/avo#2470]
### Feature
Would it be possible to install Avo in [Ruby on Jets](https://github.com/rubyonjets/jets) application? It has generators and most of the tools of Rails, so maybe it only needs tutorial of how to install.

### Current workarounds

I have no idea how to install, tried to follow installation tutorial, but it breaks on `jets generate avo:install` 

### Additional context
It might be an issue of added libraries because I get error of missing Pagy.

**Comment by adrianthedev** [comment]
I don't know if Avo will work with Ruby on Jets.
It probably won't.

AFAIK RoJ only mimics Rails' API but has a different implementation with different libraries, and because of that, Avo might not run.
I don't even know if RoJ supports Rails engines.
Maybe Ask the RoJ maintainers if Rails Engines (and Avo) would be supported?

**Comment by djolereject** [comment]
Thanks!
