### ISSUE TITLE
List of all default translations

### ISSUE THREAD

**Issue by TobiasKampAdmin** [avo-hq/avo#2848]
### Context
Looking for a list of all translation keys Avo uses.
And maybe some strings are not translated yet?

### Looking for a list of all keys
We tried starting from the demo project yml files:
https://github.com/avo-hq/main.avodemo.com/tree/main/config/locales 
But not all keys were listed there and it feels a bit like guessing to add them as we come across missing keys.
Is there a list of keys somewhere that is also updated with new releases?
I would expect a link to such list in this part of the documentation: https://docs.avohq.io/3.0/localization.html 

### Some translations missing?
Could it be that some parts of Avo are still in hardcoded strings?
A few examples in the screenshots below:
<img width="367" alt="Scherm­afbeelding 2024-06-07 om 23 02 11" src="https://github.com/avo-hq/avo/assets/60701859/76d318a6-912f-447c-87ea-48c4a0457e3d">
<img width="565" alt="Scherm­afbeelding 2024-06-07 om 23 02 32" src="https://github.com/avo-hq/avo/assets/60701859/d071f52a-f118-426f-82a0-8f0d45e9d6b3">

### Low prio but could be a general improvement (of documentation)
Low prio, low impact

**Comment by adrianthedev** [comment]
It could be that some are not translated. We'll check those that you pointed out.
The pagination one is most likely transalted in https://github.com/ddnexus/pagy

**Comment by TobiasKampAdmin** [comment]
Thanks, please note that these were just a few _examples_ of missing translations I noticed.
A list of strings you should translate when using Avo in your own language, updated on new releases, would be an ideal solution for us. We are happy to contribute to this by sharing missing translations (if this is useful for you guys) and share our default Dutch and French translations.

**Comment by TobiasKampAdmin** [comment]
For the pagination, Pagy has correct default Dutch translations in here: 
https://github.com/ddnexus/pagy/blob/master/gem/locales/nl.yml 

Could you use them in Avo by default in the same locale as set in the `avo.rb` config?
`config.locale = :nl `

**Comment by adrianthedev** [comment]
There are a few things here.

1. All translation keys that we add in Avo should be there for all present languages. Some are translated by real people that speak that language, and some are translated using Google Translate or ChatGPT
2. When we add a "magic string" that is not translated, like "Add filter", it's because we forgot to localize it, so we will not remember to make that list on each release 😅 If we remember about it, we will add it to the translation keys.
3. Thank you for contributing with those languages!
4. The `config.locale` got some upgrades in https://github.com/avo-hq/avo/pull/2855.
5. `pagy` follows the Avo locale if set, if not it will try the app's default_locale and after all of that fallback to `en`.

All of these above should work properly after we merge #2855. Some edge-cases could still happen, but that PR will fix them.

So, if you found some strings that aren't translated, please share them with us and we'll add them to the i18n files.
