### ISSUE TITLE
Add new exclude_from_actions_list option in actions

### ISSUE THREAD

**Issue by icaroryan** [avo-hq/avo#2908]
### Feature
I would like to request a new feature in AVO 3 that allows developers to exclude specific actions from the general actions list while keeping them available in other contexts like row and show view controls. This could be achieved by introducing a new option, `exclude_from_actions_list`, when defining actions.

### Current workarounds
Currently, to achieve this behavior, I need to manually exclude actions from the actions list within the index_controls block of a resource. Here is an example of the current implementation:

```rb
class Avo::Resources::FileArchive < Avo::BaseResource
  self.row_controls = -> do
    action Avo::Actions::DownloadFileArchive, style: :primary, color: :blue, icon: 'heroicons/outline/arrow-down-tray'
    show_button
  end

  self.index_controls = -> do
    actions_list exclude: Avo::Actions::DownloadFileArchive
  end

  def actions
    action Avo::Actions::DownloadFileArchive
  end
end
```

This method works, but it would be more maintainable and intuitive to have an `exclude_from_actions_list` option within the action definition itself.

### Proposed Implementation
By introducing an `exclude_from_actions_list` option within the action definition, the exclusion logic can be defined in a self-contained manner. Here is how the proposed implementation could look:

```rb
class Avo::Actions::DownloadFileArchive < Avo::BaseAction
  self.name = "Download File Archive"
  self.exclude_from_actions_list = true  # New option to exclude this action from the actions list

  # ... rest of the action definition
end
```

In the resource file, this would simplify the controls definitions:
```rb
class Avo::Resources::FileArchive < Avo::BaseResource
  self.row_controls = -> do
    action Avo::Actions::DownloadFileArchive, style: :primary, color: :blue, icon: 'heroicons/outline/arrow-down-tray'
    show_button
  end

  self.show_controls = -> do
    back_button
    action Avo::Actions::DownloadFileArchive, style: :primary, color: :blue, icon: 'heroicons/outline/arrow-down-tray'
  end

  def actions
    action Avo::Actions::DownloadFileArchive
  end
end
```

**Comment by icaroryan** [comment]
This would be a good nice-to-have, but definitely not essential, because there are other ways to do this and more important things to work on.

Also, just want to acknowledge how amazing AVO is. I've got the advanced license and I really appreciate the work you guys have been putting in.

**Comment by adrianthedev** [comment]
Hey @icaroryan.
Sorry for the late reply.

Thank you for the kind words! We're always curious to see what others are building with Avo.

Regarding the feature request, I totally understand.
It's kind of a known limitation as we implemented the custom controls as fast as we could and it's not the cleanest one.
The biggest issue being that you need to add the `action` in the `def actions` method first before using it in the controls. 
This is tied to a `get_actions` method on the resource that we use in the custom controls.
Because of that, a few things are not "great".
One of these things is that the actions list will always have all the actions declared in the `actions` method.

The proper fix would be to not depend on the `def actions` method in the first place.
Then, the actions_list would not even render if it would be empty.

So, I'm inclined to respond to you with "that's the way to do it currently" and wait until we have a proper fix for this.
The second answer is that we would take a contribution if you (or anyone reading this) would like to solve it faster.

**Comment by adrianthedev** [comment]
Related issue: https://github.com/avo-hq/avo/issues/2784

**Comment by icaroryan** [comment]
@adrianthedev Thank you for such an in-depth answer! I really appreciate you taking the time to explain the current implementation and the challenges involved.
As I get more confident with AVO, I'd love to contribute wherever I can.

**Comment by adrianthedev** [comment]
Got it! Thanks for that.
I'll go ahead and close this one in favor or https://github.com/avo-hq/avo/issues/2917
