### ISSUE TITLE
Decouple actions in the custom controls from the actions in the `def actions` method

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2917]
### Context

Right now there's a limitation of not being able to use an action in the custom controls area (show, index, edit, row) unless it's added first in the `def actions` method of the resource.

This can lead to [issues](https://github.com/avo-hq/avo/issues/2908) with displaying the actions in different contexts and doing weird gymnastics around it to support advanced use-cases.

### Proposal

Let's decouple those two and fix those issues once and for all.

**Comment by SahSantoshh** [comment]
We were able to achieve this with:
```ruby
  self.index_controls = lambda {
    attach_button
    actions_list
      action Avo::Actions::ImportApplications, style: :primary, color: :fuchsia,
                                               icon: 'heroicons/outline/arrow-down-tray'
    create_button
  }

  def actions
    action Avo::Actions::AnoterAction, icon: 'heroicons/outline/calendar-days'
  end
  ```
  
  But not anymore

**Comment by binarygit** [comment]
I could take a look into this if you like :sweat_smile:

**Comment by adrianthedev** [comment]
Yes! Please do, and Thank you!

**Comment by binarygit** [comment]
I traced how actions are registered and how actions_list is rendered. I can see that excluding an action from the action_list is done when `ActionList.new` is called because ActionList has an instance var called @exclude. 

However I can't find the logic responsible for excluding things off that list. Initializing ActionList happens here (atleast for index controls):
```ruby
      def render_index_controls(item:)
        [AttachButton.new(item: item), ActionsList.new(as_index_control: true), CreateButton.new(item: item)]
      end
```
but there's no code here that excludes actions.

I want to take a look at that code because, I think, we can add code there that checks for `Action.exclude_from_actions_list` and then excludes those actions too. 

Am I missing something? or is the code in the pro/advanced repos because custom controls falls under the advanced license? @adrianthedev

**Comment by icaroryan** [comment]
Great work!
