### ISSUE TITLE
dynamic filter not computing enum type

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#3039]
### Feature

With the current version, it's not possible to declare dynamic filters with type=enum, and have the values displayed in a select

If you model is:
```ruby
class Villa < ApplicationRecord
  enum :version, { v1: "v1", v2: "v2", v3: "v3" }
```

and your resource filters declaration will fail with: The `version` filter's `type` cannot be computed. 
```ruby
def filters
    dynamic_filter :version
```

### Current workarounds

Using a text type won't help, the values are not displayed as a select:
```ruby
  def filters
    dynamic_filter :version, type: :text, suggestions: ::Villa.versions.keys.map(&:to_s)
```

**Comment by Paul-Bob** [comment]
`dynamic_filter :version` is the same as `field :version, ..., filterable: true`.

When declaring just `dynamic_filter :version` the filter need access to the `version` field in order to work and extract the other options like `type`, `options` etc...

@jetienne in the issue description there is no field with the id `version`, can you please share also the code with the field declaration? Is important to share where the field is defined (`def fields` or `def ..._fields`)

**Comment by jetienne** [comment]
@Paul-Bob I got your answer, but what is the point then to define the filter in the filters method, when you also have to define it on the index_fields method?

My suggestion would to fallback when you search for a possible field on the given filter: first search on index_fields, and if not found on fields

**Comment by Paul-Bob** [comment]
> My suggestion would to fallback when you search for a possible field on the given filter: first search on index_fields, and if not found on fields

It makes sense for your use case, but sometimes the same field ID is used in different views. For example, a status field might be a select field in a form view and a badge field in a display view.

If we want a dynamic filter select for `status`, by declaring `dynamic_filter :status` it should pick the field from the form views even if it's also declared on the index fields. 

The correct order for assigning fields to a filter depends on the use case; there isn’t a universal rule that we could apply.

I’m closing this issue. Filtering requests are made in the `index` view. If the `index_fields` method is defined, Avo will search for fields there; otherwise, it will use the fields from the `fields` method.

I'm currently working on `options` for custom select dynamic filters which will solve your issue by declaring the options on the filter, something like:

(Check https://github.com/avo-hq/avo/issues/3026 for updates; it should be included in the next release.)

```ruby
dynamic_filter :versions,
  type: :select, 
  options: ::Villa.versions.keys.map(&:to_s)
```

![image](https://github.com/user-attachments/assets/c460cda5-d141-4ea5-b0ae-7c345cb27cf5)
