### ISSUE TITLE
Polymorphic Associations Causing N+1 Issue

### ISSUE THREAD

**Issue by vbiletskii** [avo-hq/avo#3045]
### Describe the bug
I have polymorphic associations in place, and when I try to create a `Comment` in the `User` view, I encounter an n+1 issue even though I have included the dependent association.

### Steps to Reproduce
1. You can use this repo `https://github.com/vbiletskii/polymorphic_issue` to reproduce the issue
3. Go to [localhost:3000/avo/resources/users/1](http://127.0.0.1:3000/avo/resources/users/1)
4. Click on **Create new comment**
5. Open rails logs
6. See n+1(It actually loads user and admin personal information even if I create a comment for User)

### Expected behavior & Actual behavior
Expected behavior: It loads only one record with its title (name) to display in the field.
Actual behavior: It loads all records from `types: [User, Admin]` with their titles, causing an n+1 issue.

### Models and resource files
```
class User < ApplicationRecord
  has_one :personal_information, class_name: 'Users::PersonalInformation'
  has_many :comments, as: :commentable

  delegate :first_name, :last_name, to: :personal_information, allow_nil: true

  def name
    "#{first_name} #{last_name}"
  end
end
```
```
class Admin < ApplicationRecord
  has_one :personal_information, class_name: 'Admins::PersonalInformation'
  has_many :comments, as: :commentable

  delegate :first_name, :last_name, to: :personal_information, allow_nil: true

  def name
    "#{first_name} #{last_name}"
  end
end
```
```
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end
```
```
class Avo::Resources::User < Avo::BaseResource
  self.title = :name

  def fields
    field :id, as: :number
    field :comments, as: :has_many
  end
end
```
```
class Avo::Resources::Comment < Avo::BaseResource
  def fields
    field :id, as: :idlo
    field :commentable,
      as: :belongs_to,
      polymorphic_as: :commentable,
      disabled: true,
      types: [User, Admin],
      default: -> { record }
  end
end
```

### System configuration
**Avo version**:
`3.10.1`
**Rails version**:
`7.1.3`
**Ruby version**:
`3.2.2`
**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://github.com/user-attachments/assets/011718b1-bbdd-4e52-a95a-8ea71784711d

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Interesting edge case.
Can you please try to update the `attach_scope` on the `Comment` resource?

```ruby
field :commentable,
      as: :belongs_to,
      polymorphic_as: :commentable,
      disabled: true,
      types: [User, Admin],
      default: -> { record },
      attach_scope: -> { query.include(:personal_information) }
```

The code above is untested. It might need tweaking.

**Comment by vbiletskii** [comment]
> Interesting edge case. Can you please try to update the `attach_scope` on the `Comment` resource?
> 
> field :commentable,
>       as: :belongs_to,
>       polymorphic_as: :commentable,
>       disabled: true,
>       types: [User, Admin],
>       default: -> { record },
>       attach_scope: -> { query.include(:personal_information) }
> The code above is untested. It might need tweaking.

Thanks for the help, @adrianthedev! It helps somewhat, but it still loads all associations from `types` when I just want to create a comment for one of them. Additionally, if there's another model like `Booking` (without an association like `has_many :personal_information`), it will throw an error.

**Comment by adrianthedev** [comment]
Got it @vbiletskii.
Please create a minimal reproduction repo with all the models and resources that we can troubleshoot and we'll gladly apply a solution.

Please use this guide on how to create one.

https://docs.avohq.io/3.0/technical-support.html#reproduction-repository

**Comment by vbiletskii** [comment]
> Got it [@vbiletskii](https://github.com/vbiletskii). Please create a minimal reproduction repo with all the models and resources that we can troubleshoot and we'll gladly apply a solution.
> 
> Please use this guide on how to create one.
> 
> https://docs.avohq.io/3.0/technical-support.html#reproduction-repository

@adrianthedev Here's the repository: https://github.com/vbiletskii/polymorphic-issue. Let me know if you need anything else from me - really appreciate all your help!

**Comment by Paul-Bob** [comment]
Hey @vbiletskii! Thank you for providing the reproduction repository. It was incredibly helpful in identifying the root cause of the issue.

Here’s a more detailed explanation of the issue and the recommended solution:

### Explanation of the Issue

When Avo generates the options for a `belongs_to` select field, it relies on the **resource’s title attribute**. In your setup, the title is set to `name`, so Avo attempts to call `user.name` and `admin.name` to populate the labels for the select options for `User` and `Admin` instances.

The N+1 arises because `name` is not a direct attribute of the `User` or `Admin` models, instead, it is an attribute of the associated `personal_information`. This association is required to access `first_name` and `last_name`, which are combined to form the `name`. However, because `personal_information` was not eagerly loaded with the `User` or `Admin` records, the `name` method fails to find these values, resulting in that N+1.

### Solution: Include `personal_information` in default scope

To ensure that `personal_information` is always loaded when fetching `User` and `Admin` records, you can include this association in the models’ `default_scope`. This way, any time a `User` or `Admin` record is loaded, its associated `personal_information` is loaded as well, ensuring that `first_name` and `last_name` are available to construct `name` without any extra query.

Here’s how the updated models would look:

```ruby
class Admin < ApplicationRecord
  has_one :personal_information, class_name: 'Admins::PersonalInformation'
  has_many :comments, as: :commentable

  delegate :first_name, :last_name, to: :personal_information, allow_nil: true

  def name
    "#{first_name} #{last_name}"
  end

  default_scope -> { includes(:personal_information) }
end
```

And 

```ruby
class User < ApplicationRecord
  has_one :personal_information, class_name: 'Users::PersonalInformation'
  has_many :comments, as: :commentable

  delegate :first_name, :last_name, to: :personal_information, allow_nil: true

  def name
    "#{first_name} #{last_name}"
  end

  default_scope -> { includes(:personal_information) }
end
```
While adding `personal_information` to the `default_scope` is generally effective, Avo also provides the [`self.includes`](https://docs.avohq.io/3.0/resources.html#self.includes) and [`self.single_includes`](https://docs.avohq.io/3.0/resources.html#self.single_includes) options. These options allow you to manually include `personal_information` on specific scopes within Avo. 

Since `personal_information` will likely be required in most cases when querying `User` and `Admin` records, adding it to the `default_scope` at the model level simplifies implementation and ensures coverage for all scenarios.

You can also use the `attach_scope` on the polymorphic field to include the `personal_information`:

```ruby
class Avo::Resources::Comment < Avo::BaseResource
  self.includes = []
  # self.search = {
  #   query: -> { query.ransack(id_eq: params[:q], m: "or").result(distinct: false) }
  # }

  def fields
    field :id, as: :idlo
    field(
      :commentable,
      as: :belongs_to,
      polymorphic_as: :commentable,
      disabled: true,
      types: [User, Admin],
      attach_scope: -> { query.includes(:personal_information) },
      default: -> { record }
    )
  end
end
```

However, I still recommend including `personal_information` at the model level, as it will provide consistent coverage both within and outside Avo.

Let me know if this helps, or if you have further questions!
