### ISSUE TITLE
custom dynamic filters > tags field shows values i.so. labels in dropdown

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3138]
### Describe the bug
see https://www.loom.com/share/7e965c0a81ed4f4d81d56ef7f8113335

### Steps to Reproduce
```ruby
def filters
    dynamic_filter :my_field, as: :tags, suggestions: [
            {value: 1, label: "foo"},
            {value: 2, label: "bar"}, 
          ]
end
```

### System configuration
**Avo version**: 3.11.6

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [X] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hi @pjmuller,

I wanted to highlight that tags filters and tags fields have different feature sets. Currently, tags filters support suggestions only as an array of hashes, as outlined in the [documentation](https://docs.avohq.io/3.0/dynamic-filters.html#suggestions).

For this reason, I view it more as a feature request rather than a bug.

 I made [this PR](https://github.com/avo-hq/avo-dynamic_filters/pull/64) that implements `label`, `value` and `avatar` as a hash for tags filters suggestions.

**Comment by pjmuller** [comment]
@Paul-Bob thanks a lot for the quick resolution, and perfect to name it a feature request.
It's just a bit confusing (for both avo maintainers as users) that there are so many ways to provide suggestions.

With great power/flexibility comes great responsibility ;)
