### ISSUE TITLE
tags field glitches

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3152]
### Describe the bug
see https://www.loom.com/share/e4957f3435674b19853f5276c5e722a0

The video is made in context of an `action` however the exact same behavior is present inside of a standard `resource`

### Steps to Reproduce
```ruby
   field :foobar, as: :tags, mode: :select, suggestions: ....
```

### System configuration
**Avo version**: 3.11.6

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

### Additional context
We very extensively use the tags field as the search functionality makes it much more user friendly than a regular `select`

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [X] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hey @pjmuller I guess you want to apply [close_on_select](https://docs.avohq.io/3.0/fields/tags.html#close_on_select) option on that field. Otherwise, it will not automatically close when selecting an option.

Closing this issue as [close_on_select](https://docs.avohq.io/3.0/fields/tags.html#close_on_select) should resolve the problem. However, feel free to reopen it if you continue to experience glitches after applying this option.

**Comment by pjmuller** [comment]
WORKS like a charm 💎
