### ISSUE TITLE
plural name not used in search

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3302]
### Describe the bug
See screenshot

we use plural_name to dynamically set a resource name
```ruby
class Avo::Resources::Person  < Avo::BaseResource
  def plural_name
      "Activiteiten" # simplified code, we actually get the name dyn. from the DB
  end
end
```

This works well for the resource title as well as for breadcrumbs but not for search / global search / belongs_to fields

![Screenshot 2024-10-02 at 16 54 14](https://github.com/user-attachments/assets/dc1369e4-a71f-4dfe-aed0-850d5e1c6838)

### System configuration
**Avo version**: 3.13.1

**Rails version**: 7.2.1

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [X] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [X] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [X] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by enderahmetyurt** [comment]
I did a quick look at it. Actually it would work regarding this line https://github.com/avo-hq/avo/blob/main/app/controllers/avo/search_controller.rb#L64 but I couldn't get 🧐

**Comment by adrianthedev** [comment]
> I did a quick look at it. Actually it would work regarding this line [`main`/app/controllers/avo/search_controller.rb#L64](https://github.com/avo-hq/avo/blob/main/app/controllers/avo/search_controller.rb?rgh-link-date=2024-10-03T15%3A20%3A42Z#L64) but I couldn't get 🧐

That's exactly where the patch should be applied

**Comment by Paul-Bob** [comment]
Hey @pjmuller

Overriding the `plural_name` as a class method will fix the search title.

```ruby
class Avo::Resources::Person  < Avo::BaseResource
  def self.plural_name
      "Activiteiten" # simplified code, we actually get the name dyn. from the DB
  end
end
```

More details:
- `plural_name` is a class method.
- It is sometimes called from an instance of the resource, and other times directly from the resource class.
- When a resource instance calls it, it delegates the call to the class method.
- If you override `plural_name` only at the instance level, the override will work when called from the instance.
- However, if you call `plural_name` directly from the class, it won’t use the instance-specific override.
- Overriding `plural_name` at the class level will work for both instance and direct class calls since both reference the modified class method.

**Comment by pjmuller** [comment]
@Paul-Bob  Works like a charm ❤ 
Might be good to add your (very clear) bullet points in the documentation :)

**Comment by adrianthedev** [comment]
Yes. A guide is warranted.
Let's create an issue in the docs for it.
