### ISSUE TITLE
`KeyValueField`s when not backed by a Model...

### ISSUE THREAD

**Issue by ncsmith24** [avo-hq/avo#3410]
### Context

We are using https://docs.avohq.io/3.0/resources.html#manually-defining-resources to set up some resources that are not directly backed by existing models (and, consequently, have fields that are not backed by attributes)

This has been working pretty well, until a recent change that causes any `KeyValueField` fields that are not backed by an attribute to break, this is due to a new call to the `*_will_change!` method provided by ActiveModel::Dirty.

We were able to set up a work-around in our BaseFakeModel class, which resources with this issue inherit from:

```ruby

class BaseFakeModel
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations
  extend ActiveModel::Naming

  class << self
    def field(name, **opts)
      @@fields ||= []
      @@fields << name

      attr_accessor name
      define_method(:"#{name}_will_change!") { send(name) }
    end
...
```

So no change needed necessarily, but I wasn't sure whether Avo resources that aren't backed by existing models are meant to be "first class citizens", if so it would probably be good to have a more out-of-the-box solution for this kind of use case. If not then we are happy to just use the fix above.

### System configuration

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by Paul-Bob** [comment]
Hi @ncsmith24 thanks for reaching out.

---

> This has been working pretty well, until a recent change that causes any KeyValueField fields that are not backed by an attribute to break, this is due to a new call to the *_will_change! method provided by ActiveModel::Dirty.

This call marks the key-value field as "dirty" on the record, which is essential because, during edits, if the user merely reorders the rows, the change isn’t automatically detected. Therefore, it must be manually flagged as dirty to ensure the new order is correctly updated.

---

> We were able to set up a work-around in our BaseFakeModel class, which resources with this issue inherit from:

Great work-around! Have you tried `include ActiveModel::Dirty` on the `BaseFakeModel`? (let me know if that also works)

---

> So no change needed necessarily, but I wasn't sure whether Avo resources that aren't backed by existing models are meant to be "first class citizens"

Currently, Avo resources are closely tied to Active Record, and much of the development has been centered around it. There’s a roadmap issue called "resource adapters" aimed at natively supporting resources backed by APIs or array models. We've done some experimental development in this area, but it's currently on hold. Feel free to subscribe to this issue to stay updated on its progress: [Issue #1418](https://github.com/avo-hq/avo/issues/1418).

Regarding these resources as "first-class citizens," I'd like to say yes; however, since our development is primarily centered around Active Record and relies on having an underlying model, issues like this may arise periodically until native support is fully implemented.

---


I'm closing the issue as no further action is needed, but let's keep the discussion open.
