### ISSUE TITLE
Only depend on required rails gems

### ISSUE THREAD

**Issue by pmackay** [avo-hq/avo#540]
It would be very helpful if Avo could list the dependencies on the specific rails gems it needs, instead of including rails as a single dependency. That way, apps that follow a similar pattern wont also pull in unnecessary rails modules that they dont use (e.g. less frequently used modules such as actionmailbox, actioncable...).

**Comment by adrianthedev** [comment]
This is interesting @pmackay. How would we go about doing that? Should we tweak our `spec.add_dependency "rails", ">= 6.0"` in the gemspec?

**Comment by luonet** [comment]
Hi @pmackay 

I think it's up to you to choose the rails modules, and it's no relation to the `avo` gem.

You can choose the gems you want in `config/application.rb` of your rails app:
Instead of  `require "rails/all"`, you can use like `require "action_controller/railtie"` to choose your wanted modules.

So, @adrianthedev I think this is not an `avo` issue.
