### ISSUE TITLE
Editing a record from has_many doesn't prefill the belongs_to field

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#715]
### Describe the bug

Regarding the has_many:
For me it seems that the when editing a has_many item, the belongs_to is set, but there is no "title". 
![image](https://user-images.githubusercontent.com/1334409/156756326-7d9063b0-4c54-4fb6-be36-538e53343a69.png)

and on the course itself:

![image](https://user-images.githubusercontent.com/1334409/156756348-ea6b7667-21a0-4c71-ab71-8da759792063.png)

**Comment by adrianthedev** [comment]
Hey, @jony1993 what version of Avo are you experiencing this? We fixed some of those. Can you try latest version please?

**Comment by jony1993** [comment]
@adrianthedev 
It was working on v1.23.0.
But it seems to be not working on v1.24.0 (I tried out the "order_feature")

**Comment by jony1993** [comment]
Hi @adrianthedev,

I double checked it again.
Atm we are using avo (1.22.3) and not 1.23.0. Sorry for the confusion...
I double checked also the "Course Link" error, and its working also on the branch 1.24.1.
So I think we could close the ticket...

Sorry for the confusion

**But what I found out:**
I found out that avo caches the reponses in our redis cache with a ttl of -1.
And somehow it seems that the cached responses were not invalidated.

So the overall "process" was like this:
- We saw on our staging staging system that on some has_many resources some fields were missing
- We reported the issue to you and you fixed it
- We updated our local avo version, there it was working now (because redis wipes all data there after every start) and pushed it to staging
- On Staging it was still the same error (even after some days) and we manually had to wipe the redis cache.

Thats why we also had some other weird issues in the past.  E.g. We did change the root.path of avo and still saw from time to time the "old" root.path resource links, which then led to 404/error pages

**Comment by adrianthedev** [comment]
Ok. I'm glad the issue is fixed. For performance resons we do cache some data on index. More on that [here](https://docs.avohq.io/1.0/customization.html#cache-resources-on-index-view). I'll check some more to see about that -1 ttl. That should be invalidated at some point. 
Thanks for writing back.

**Comment by adrianthedev** [comment]
Checked and yes, the cache time is -1. Fixing that this week https://github.com/avo-hq/avo/issues/719
