### ISSUE TITLE
OAuth integration

### ISSUE THREAD

**Issue by veelenga** [avo-hq/avo#885]
### Context

Hey there. We are considering using Avo for a future internal admin system and a few questions popped up.

1. Do you expect any issues using OAuth instead of a built-in Authorization?
2. Are there any examples/docs using OAuth with Avo?

**Comment by adrianthedev** [comment]
Hey @veelenga. We don't have any example using OAuth with Avo because each setup might differ, but we know for sure that other customers use other kinds of authentication, OAuth included.

To do authorization right with Avo, like in a regular Rails app, you need to do two things:

1. Hide the Avo engine behind a route filter. The [docs](https://docs.avohq.io/2.0/authentication.html#filter-out-requests) show you how to do that for regular authentication.
2. Tell Avo how to fetch the `current_user`. That piece of configuration is a block so you should be able to customize it as much as you need it.

I'd love to pair with you on this and extract an example to add to the docs.

**Comment by veelenga** [comment]
@adrianthedev thanks a lot. 

I will use this issue once more related questions pop up or we will be able to share an example for docs.

**Comment by adrianthedev** [comment]
Sure. That sounds good!

Thank you for the sponsorship! I appreciate it 🙏
